/*
 * Offline benchmark + crossover-chart generator (Phase 5c).
 *
 * Draws the CloudRoaring pay-per-use cost curves against a flat Redis-HA node and marks where they cross,
 * straight from the SHIPPED estimator (`estimateCost`) + the default pricing — so the published chart can
 * never drift from the library's own numbers. Wall-clock latency lives here (not in CI) because shared
 * runners are too noisy to gate on; the deterministic anchors are gated in tests/bench/anchors.test.ts.
 *
 * Run with `pnpm bench` (builds first). Regenerates, in place and deterministically (no timestamps):
 *   - bench/crossover.svg           self-contained chart (used by docs/benchmarks.md)
 *   - bench/results.json            the numbers behind the chart
 *   - site/benchmarks.html          chart inlined + stats table (between BENCH markers)
 *   - docs/benchmarks.md            chart <img> + stats table (between BENCH markers)
 *
 * Imports the CJS build (@cloudbitmaps/roaring) on purpose: the ESM bundle pulls `roaring`'s named exports, which
 * Node's ESM loader can't statically resolve for a native CJS addon.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { estimateCost, AWS_US_EAST_1_ONDEMAND } = require('@cloudbitmaps/roaring');

const ROOT = path.resolve(__dirname, '..');
const P = AWS_US_EAST_1_ONDEMAND;
const REDIS = P.redis.monthlyUSD;
const GIB = 1024 ** 3;

// ── The numbers, all from the shipped estimator ──────────────────────────────────────────────────
const base = { avgItemKiB: 8, cacheHitRate: 0, topology: 'B' };
const costWrites = (x) =>
  estimateCost({
    segments: [{ sizeBytes: 0 }],
    topology: 'B',
    workload: { ...base, writesPerSec: x },
  }).monthlyUSD.total;
const costReads = (x) =>
  estimateCost({
    segments: [{ sizeBytes: 0 }],
    topology: 'B',
    workload: { ...base, readsPerSec: x },
  }).monthlyUSD.total;

const crossReport = estimateCost({
  segments: [{ sizeBytes: 0 }],
  topology: 'B',
  workload: base,
});
const writeCross = crossReport.redisCrossover.writesPerSec;
const readCross = crossReport.redisCrossover.readsPerSec;

const atRestBytes = 1.2 * GIB; // reference: ~1.2 GiB at rest, no traffic
const atRest = estimateCost({ segments: [{ sizeBytes: atRestBytes }] });

const results = {
  note: 'Generated by `pnpm bench` from the shipped estimateCost() + default pricing. Do not edit by hand.',
  pricing: P.name,
  redisBaselineUSD: REDIS,
  assumptions: {
    avgItemKiB: base.avgItemKiB,
    cacheHitRate: base.cacheHitRate,
    topology: base.topology,
  },
  writeCrossoverPerSec: round(writeCross, 2),
  readCrossoverPerSec: round(readCross, 2),
  atRest: {
    sizeGiB: round(atRestBytes / GIB, 3),
    monthlyUSD: round(atRest.monthlyUSD.total, 4),
    pctOfRedis: round((atRest.monthlyUSD.total / REDIS) * 100, 3),
    verdict: atRest.verdict,
  },
};

// ── The chart ────────────────────────────────────────────────────────────────────────────────────
// Colours are `var(--token, literal)` because this ONE svg is consumed two ways: inlined into
// site/benchmarks.html (where the custom properties resolve, so the chart follows the page's light/dark
// toggle) and written to bench/crossover.svg for docs/benchmarks.md, where it is an <img> with no
// stylesheet in scope and every var() falls back to the literal. The literals are therefore a coherent
// LIGHT palette — they are what GitHub renders.
//
// Two colours deliberately stay literal or muted rather than taking a semantic token:
//   · redis   — a third-party baseline, outside our token system. Verified 3.43:1 on the dark ground and
//               5.36:1 on white, so it clears 1.4.11 for non-text in both themes. It is used only for the
//               LINE and the band fill, never for a text label, because 3.43:1 fails AA for 11px text.
//   · the lose-zone label — --cb-no is 4.30:1 on the dark ground, just under AA, so the annotation takes
//               --cb-muted and lets the band fill plus its own wording carry the meaning. Nothing here is
//               encoded by colour alone.
const COL = {
  card: 'var(--cb-surface, #ffffff)',
  hair: 'var(--cb-rule, #e4e8ed)',
  ink: 'var(--cb-ink, #15181e)',
  inkSoft: 'var(--cb-muted, #3c4450)',
  muted: 'var(--cb-faint, #69737f)',
  cr: 'var(--cb-cyan, #34378f)', // the CloudBitmaps curve — "this is the number"
  redis: '#d9480f', // Redis baseline. Non-text only; see above.
  win: 'var(--cb-ok, #1e7a52)',
};
const FONT = "var(--cb-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif)";

const W = 760;
const HEADER = 96;
const PANEL_H = 300;
const H = HEADER + PANEL_H * 2;
const Y_MAX = 600; // shared y-axis ceiling for both panels
const X_MAX_WRITES = 45;
const X_MAX_READS = 850;

// Fail loud if a curve would exceed the axis — py()'s clamp would otherwise silently flatten it, exactly the
// kind of drift this chart exists to prevent. Raise Y_MAX (and re-run `pnpm bench`) if pricing pushes higher.
{
  const peakCost = Math.max(costWrites(X_MAX_WRITES), costReads(X_MAX_READS), REDIS);
  if (peakCost > Y_MAX) {
    throw new Error(
      `chart Y_MAX=${Y_MAX} is below the peak plotted cost $${peakCost.toFixed(0)} — raise Y_MAX in bench/run.cjs`,
    );
  }
}

const svg = [
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" font-family="${FONT}" role="img" aria-label="CloudRoaring vs flat Redis-HA cost crossover chart">`,
  // rx=0: the site's design language has no rounded corners, and this chart sits inline in it.
  `<rect x="1" y="1" width="${W - 2}" height="${H - 2}" rx="0" fill="${COL.card}" stroke="${COL.hair}"/>`,
  // header
  `<text x="28" y="34" font-size="17" font-weight="700" fill="${COL.ink}">Where pay-per-use crosses a flat Redis-HA node</text>`,
  `<text x="28" y="56" font-size="12.5" fill="${COL.muted}">${esc(P.name)} · ${base.avgItemKiB} KiB items · cache off · flat Redis-HA = $${REDIS}/mo</text>`,
  // legend on its own row so it never collides with the title
  legend(28, 78),
  panel(
    HEADER,
    'Sustained writes — the metered cost driver',
    'writes / sec',
    costWrites,
    writeCross,
    [0, 15, 30, 45],
    X_MAX_WRITES,
  ),
  panel(
    HEADER + PANEL_H,
    'Sustained reads (Topology-B warm, strongly-consistent)',
    'reads / sec',
    costReads,
    readCross,
    [0, 250, 500, 750],
    X_MAX_READS,
  ),
  `</svg>`,
].join('\n');

function legend(x0, y) {
  const items = [
    { c: COL.cr, t: 'CloudRoaring (pay-per-use)' },
    { c: COL.redis, t: 'Redis HA (flat)' },
  ];
  let x = x0;
  const parts = [];
  for (const { c, t } of items) {
    parts.push(
      `<line x1="${x}" y1="${y}" x2="${x + 16}" y2="${y}" stroke="${c}" stroke-width="3"/>`,
      `<text x="${x + 22}" y="${y + 4}" font-size="12" fill="${COL.inkSoft}">${t}</text>`,
    );
    x += 22 + t.length * 6.3 + 26;
  }
  return parts.join('');
}

function panel(top, title, xLabel, costFn, crossover, xTicks, xMax) {
  const ML = 66;
  const MR = 26;
  const MT = 46;
  const MB = 54;
  const plotL = ML;
  const plotR = W - MR;
  const plotT = top + MT;
  const plotB = top + PANEL_H - MB;
  const plotW = plotR - plotL;
  const plotH = plotB - plotT;

  const yMax = Y_MAX;
  const yTicks = [0, 200, 400, 600];
  const px = (x) => plotL + (x / xMax) * plotW;
  const py = (v) => plotB - (Math.min(v, yMax) / yMax) * plotH;

  const N = 80;
  const pts = [];
  for (let i = 0; i <= N; i++) {
    const x = (i / N) * xMax;
    pts.push(`${px(x).toFixed(1)},${py(costFn(x)).toFixed(1)}`);
  }
  const crX = px(crossover);
  const redisY = py(REDIS);

  const out = [`<g>`];
  out.push(
    `<text x="${ML}" y="${top + 26}" font-size="13.5" font-weight="600" fill="${COL.ink}">${title}</text>`,
  );
  // win / lose bands
  out.push(
    `<rect x="${plotL}" y="${plotT}" width="${(crX - plotL).toFixed(1)}" height="${plotH}" fill="${COL.win}" opacity="0.06"/>`,
    `<rect x="${crX.toFixed(1)}" y="${plotT}" width="${(plotR - crX).toFixed(1)}" height="${plotH}" fill="${COL.redis}" opacity="0.06"/>`,
    `<text x="${(plotL + (crX - plotL) / 2).toFixed(1)}" y="${plotT + 18}" font-size="11" fill="${COL.win}" text-anchor="middle" font-weight="600">cheaper than Redis</text>`,
    `<text x="${(crX + (plotR - crX) / 2).toFixed(1)}" y="${plotT + 18}" font-size="11" fill="${COL.inkSoft}" text-anchor="middle" font-weight="600">Redis is cheaper</text>`,
  );
  // y grid + labels
  for (const t of yTicks) {
    const y = py(t);
    out.push(
      `<line x1="${plotL}" y1="${y.toFixed(1)}" x2="${plotR}" y2="${y.toFixed(1)}" stroke="${COL.hair}" stroke-width="1"/>`,
      `<text x="${plotL - 10}" y="${(y + 4).toFixed(1)}" font-size="11" fill="${COL.muted}" text-anchor="end">$${t}</text>`,
    );
  }
  // x labels
  for (const t of xTicks) {
    out.push(
      `<text x="${px(t).toFixed(1)}" y="${plotB + 20}" font-size="11" fill="${COL.muted}" text-anchor="middle">${t}</text>`,
    );
  }
  out.push(
    `<text x="${((plotL + plotR) / 2).toFixed(1)}" y="${plotB + 42}" font-size="12" fill="${COL.inkSoft}" text-anchor="middle">${xLabel}</text>`,
  );
  // redis flat line
  out.push(
    `<line x1="${plotL}" y1="${redisY.toFixed(1)}" x2="${plotR}" y2="${redisY.toFixed(1)}" stroke="${COL.redis}" stroke-width="2" stroke-dasharray="6 4"/>`,
  );
  // CloudRoaring curve
  out.push(
    `<polyline points="${pts.join(' ')}" fill="none" stroke="${COL.cr}" stroke-width="2.5"/>`,
  );
  // crossover marker
  out.push(
    `<line x1="${crX.toFixed(1)}" y1="${plotT}" x2="${crX.toFixed(1)}" y2="${plotB}" stroke="${COL.muted}" stroke-width="1" stroke-dasharray="3 3"/>`,
    `<circle cx="${crX.toFixed(1)}" cy="${redisY.toFixed(1)}" r="4.5" fill="${COL.cr}"/>`,
    // BELOW the baseline, not above it. The curve crosses the flat Redis line exactly here by definition, so
    // a label at `redisY - 10` is guaranteed to be printed over the curve's own stroke — which it was, most
    // illegibly on the reads panel. Below-right of the crossing is the one quadrant the curve has just left.
    `<text x="${(crX + 8).toFixed(1)}" y="${(redisY + 20).toFixed(1)}" font-size="12" font-weight="700" fill="${COL.cr}">crossover ≈ ${crossover.toFixed(crossover < 100 ? 1 : 0)} /s</text>`,
  );
  out.push(`</g>`);
  return out.join('\n');
}

// ── Stats tables ─────────────────────────────────────────────────────────────────────────────────
const rows = [
  [
    'At-rest (1.2 GiB, no traffic)',
    `$${results.atRest.monthlyUSD.toFixed(2)}/mo`,
    `${results.atRest.pctOfRedis}% of Redis`,
    esc(results.atRest.verdict),
  ],
  [
    'Write crossover',
    `${results.writeCrossoverPerSec} writes/s`,
    '8 KiB items',
    'past here Redis wins',
  ],
  [
    'Read crossover',
    `${results.readCrossoverPerSec} reads/s`,
    'Topology-B, cache off',
    'past here Redis wins',
  ],
  ['Redis-HA baseline', `$${REDIS}/mo`, 'flat', 'the comparison line'],
];
// NOTE — there is deliberately no HTML table here any more. site/benchmarks.html hand-writes its own
// "Cost anchors" panel, which is a superset of these four rows (it adds count(), segment publishes and the
// A ∩ B chunk-skipping row) in the site's own .tpanel form with verdict chips and a basis column. Injecting
// this table beside it would print four of those numbers twice in two different styles. The site's copies are
// instead verified against bench/results.json by scripts/site-figures.cjs, in BOTH directions — every anchor
// must appear, and no money figure may appear that no source accounts for. The markdown table below is still
// injected, because docs/benchmarks.md has no hand-written equivalent.
const mdTable =
  `| Scenario | Value | Basis | Verdict |\n| --- | --- | --- | --- |\n` +
  rows.map((r) => `| ${r[0]} | **${r[1]}** | ${r[2]} | ${r[3]} |`).join('\n');

// ── Write / inject ───────────────────────────────────────────────────────────────────────────────
write('bench/crossover.svg', `<?xml version="1.0" encoding="UTF-8"?>\n${svg}\n`);
write('bench/results.json', JSON.stringify(results, null, 2) + '\n');
// The site takes the svg inline (so it inherits the page's theme tokens); the docs take it as an <img> and
// carry the stats table the site hand-writes. Only the regions passed are touched, so a file is not required
// to host every marker pair — but a marker pair that IS named must exist, or replaceRegion throws.
inject('site/benchmarks.html', { CHART: svg });
inject('docs/benchmarks.md', {
  CHART: `![CloudRoaring vs flat Redis-HA cost crossover](../bench/crossover.svg)`,
  STATS: mdTable,
});

function inject(rel, regions) {
  const file = path.join(ROOT, rel);
  let s = fs.readFileSync(file, 'utf8');
  for (const [name, body] of Object.entries(regions)) s = replaceRegion(s, name, body, rel);
  fs.writeFileSync(file, s);
  log(rel);
}
function replaceRegion(s, name, body, rel) {
  const start = `<!-- BENCH:${name}:START -->`;
  const end = `<!-- BENCH:${name}:END -->`;
  const i = s.indexOf(start);
  const j = s.indexOf(end);
  // Throwing rather than warning is deliberate: a silently-skipped region publishes a page with a stale or
  // empty figure, which is worse than a failed run. This is exactly how the site rebuild broke `pnpm bench` —
  // the markers were dropped with the old markup and nothing noticed until the next run.
  if (i === -1 || j === -1) throw new Error(`missing BENCH:${name} markers in ${rel}`);
  return s.slice(0, i + start.length) + '\n' + body + '\n' + s.slice(j);
}
function write(rel, body) {
  fs.writeFileSync(path.join(ROOT, rel), body);
  log(rel);
}
function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function round(n, d) {
  const f = 10 ** d;
  return Math.round(n * f) / f;
}
function log(rel) {
  console.log(`  wrote ${rel}`);
}

console.log(
  `bench: writeCross=${results.writeCrossoverPerSec}/s readCross=${results.readCrossoverPerSec}/s atRest=$${results.atRest.monthlyUSD}/mo (${results.atRest.pctOfRedis}% of Redis, ${results.atRest.verdict})`,
);
