/*
 * Offline benchmark + crossover-chart generator.
 *
 * Draws the CloudBitmaps pay-per-use read-cost curve against one Redis-HA cluster and marks where they cross,
 * straight from the SHIPPED estimator (`estimateCost`) at the default rates, against the one cluster the library
 * names (`ONE_REDIS_HA_CLUSTER`), not the Redis the data would need — so the published chart can never drift
 * from the library's own numbers. `--check` (`pnpm bench:check`, in CI) renders everything in memory and fails
 * when a file this script writes is not what it would write now; tests/bench/anchors.test.ts holds the figures to
 * the estimator as well.
 *
 * There is ONE axis, sustained point reads, because the loaded store has no per-id write: data enters as a
 * generation (one object PUT, a few when multipart), which the estimator prices as `loadsPerMonth` rather than
 * as a rate. A write panel would plot a term the model does not have.
 *
 * Run with `pnpm bench` (builds first), or `pnpm bench:check` to verify. Regenerates, in place and
 * deterministically (no timestamps):
 *   - bench/crossover.svg           self-contained chart (used by docs/benchmarks.md)
 *   - bench/results.json            the numbers behind the chart
 *   - site/benchmarks.html          chart inlined (between BENCH markers)
 *   - docs/benchmarks.md            chart <img> + stats table (between BENCH markers)
 *
 * `require()` loads @cloudbitmaps/core, which ships ESM only, through Node's `require(esm)` — unflagged from 22.12,
 * the floor the packages declare. There is no CJS build. Core, not the flavor: this is arithmetic, and the flavor
 * would load the native addon for nothing.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const {
  estimateCost,
  AWS_US_EAST_1_ONDEMAND,
  ONE_REDIS_HA_CLUSTER,
} = require('@cloudbitmaps/core');

const ROOT = path.resolve(__dirname, '..');
const check = process.argv.includes('--check');
/** Under `--check`, every file whose rendering differs from what is on disk. */
const stale = [];
// The chart is one cluster against pay-per-use, whatever the data size: the default profile sizes Redis to the data
// instead, which is the estimator's verdict, not this chart's line.
const P = { ...AWS_US_EAST_1_ONDEMAND, redis: ONE_REDIS_HA_CLUSTER };
const REDIS = ONE_REDIS_HA_CLUSTER.monthlyUSD;
const GIB = 1024 ** 3;

// ── The numbers, all from the shipped estimator ──────────────────────────────────────────────────
// Cache off is the pessimal posture, chosen so the published figure cannot flatter us: every point read is one
// object GET. The estimator evaluates the crossover at whatever hit rate it is given, so a caller with a warm
// cache gets a higher number from the same function.
const base = { cacheHitRate: 0 };
const costReads = (x) =>
  estimateCost({
    segments: [{ sizeBytes: 0 }],
    workload: { ...base, readsPerSec: x },
    pricing: P,
  }).monthlyUSD.total;

const crossReport = estimateCost({ segments: [{ sizeBytes: 0 }], workload: base, pricing: P });
const readCross = crossReport.redisCrossover.readsPerSec;

const atRestBytes = 1.2 * GIB; // reference: ~1.2 GiB at rest, no traffic
const atRest = estimateCost({ segments: [{ sizeBytes: atRestBytes }], pricing: P });
// The reference set against the Redis the estimator's default prices for it. The line is drawn against one cluster,
// which is more than that set needs, so the benchmarks page says so, and where the line would sit against it: on the
// line's own basis, with no stored bytes, so the two rates differ only in the Redis.
const sizedRef = estimateCost({ segments: [{ sizeBytes: atRestBytes }] }).redisBaseline;
const sizedCluster = sizedRef.cluster;
const refLine = estimateCost({
  segments: [{ sizeBytes: 0 }],
  workload: base,
  pricing: { ...P, redis: { monthlyUSD: sizedRef.monthlyUSD } },
}).redisCrossover.readsPerSec;

const results = {
  note:
    'Generated by `pnpm bench` from the shipped estimateCost(), at the default rates: the line against ' +
    'ONE_REDIS_HA_CLUSTER, and referenceRedis at the Redis the default profile sizes for the reference set. ' +
    'Checked by `pnpm bench:check`. Do not edit by hand.',
  pricing: P.name,
  redisBaselineUSD: REDIS,
  assumptions: {
    cacheHitRate: base.cacheHitRate,
  },
  readCrossoverPerSec: round(readCross, 2),
  atRest: {
    sizeGiB: round(atRestBytes / GIB, 3),
    monthlyUSD: round(atRest.monthlyUSD.total, 4),
    pctOfRedis: round((atRest.monthlyUSD.total / REDIS) * 100, 3),
    verdict: atRest.verdict,
  },
  referenceRedis: {
    monthlyUSD: round(sizedRef.monthlyUSD, 2),
    cluster: `${sizedCluster.nodes} × ${sizedCluster.nodeType}`,
    readCrossoverPerSec: round(refLine, 2),
  },
};

// ── The chart ────────────────────────────────────────────────────────────────────────────────────
// Colours are `var(--token, literal)` because this ONE svg is consumed two ways: inlined into
// site/benchmarks.html (where the custom properties resolve, so the chart follows the page's light/dark
// toggle) and written to bench/crossover.svg for docs/benchmarks.md, where it is an <img> with no
// stylesheet in scope and every var() falls back to the literal. The literals are therefore a coherent
// LIGHT palette — they are what GitHub renders.
//
// Two colours deliberately stay literal or muted rather than taking a semantic token:
//   · redis   — a third-party baseline, outside our token system. Verified 3.43:1 on the dark ground and
//               5.36:1 on white, so it clears 1.4.11 for non-text in both themes. It is used only for the
//               LINE and the band fill, never for a text label, because 3.43:1 fails AA for 11px text.
//   · the lose-zone label — --cb-no is 4.30:1 on the dark ground, just under AA, so the annotation takes
//               --cb-muted and lets the band fill plus its own wording carry the meaning. Nothing here is
//               encoded by colour alone.
const COL = {
  card: 'var(--cb-surface, #ffffff)',
  hair: 'var(--cb-rule, #e4e8ed)',
  ink: 'var(--cb-ink, #15181e)',
  inkSoft: 'var(--cb-muted, #3c4450)',
  muted: 'var(--cb-faint, #69737f)',
  cr: 'var(--cb-cyan, #34378f)', // the CloudBitmaps curve — "this is the number"
  redis: '#d9480f', // Redis baseline. Non-text only; see above.
  win: 'var(--cb-ok, #1e7a52)',
};
const FONT = "var(--cb-sans, -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif)";

const W = 760;
const HEADER = 96;
const PANEL_H = 300;
const H = HEADER + PANEL_H;
const Y_MAX = 600; // y-axis ceiling; the ticks below must end on it
const Y_TICKS = [0, 200, 400, 600];
const X_MAX_READS = 500;
const X_TICKS_READS = [0, 100, 200, 300, 400, 500];

// Fail loud if the curve would exceed the axis — py()'s clamp would otherwise silently flatten it, exactly the
// kind of drift this chart exists to prevent. Raise Y_MAX (and re-run `pnpm bench`) if pricing pushes higher.
{
  const peakCost = Math.max(costReads(X_MAX_READS), REDIS);
  if (peakCost > Y_MAX) {
    throw new Error(
      `chart Y_MAX=${Y_MAX} is below the peak plotted cost $${peakCost.toFixed(0)} — raise Y_MAX in bench/run.cjs`,
    );
  }
  // And the other direction: a crossover past the x-axis would have no marker to draw, and the reader would see
  // a curve that never crosses — the opposite of the honest picture.
  if (readCross > X_MAX_READS) {
    throw new Error(
      `read crossover ${readCross.toFixed(2)}/s is past X_MAX_READS=${X_MAX_READS} — widen the axis in bench/run.cjs`,
    );
  }
}

const svg = [
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" font-family="${FONT}" role="img" aria-label="CloudBitmaps against one Redis-HA cluster: where the cost crosses">`,
  // rx=0: the site's design language has no rounded corners, and this chart sits inline in it.
  `<rect x="1" y="1" width="${W - 2}" height="${H - 2}" rx="0" fill="${COL.card}" stroke="${COL.hair}"/>`,
  // header
  `<text x="28" y="34" font-size="17" font-weight="700" fill="${COL.ink}">Where pay-per-use crosses one Redis-HA cluster</text>`,
  `<text x="28" y="56" font-size="12.5" fill="${COL.muted}">${esc(P.name)} · cache off · one Redis-HA cluster = $${REDIS}/mo, whatever the data size</text>`,
  // legend on its own row so it never collides with the title
  legend(28, 78),
  panel(
    HEADER,
    'Sustained point reads (object GETs, cache off)',
    'reads / sec',
    costReads,
    readCross,
    X_TICKS_READS,
    X_MAX_READS,
  ),
  `</svg>`,
].join('\n');

function legend(x0, y) {
  const items = [
    { c: COL.cr, t: 'CloudBitmaps (pay-per-use)' },
    { c: COL.redis, t: 'Redis HA cluster (flat)' },
  ];
  let x = x0;
  const parts = [];
  for (const { c, t } of items) {
    parts.push(
      `<line x1="${x}" y1="${y}" x2="${x + 16}" y2="${y}" stroke="${c}" stroke-width="3"/>`,
      `<text x="${x + 22}" y="${y + 4}" font-size="12" fill="${COL.inkSoft}">${t}</text>`,
    );
    x += 22 + t.length * 6.3 + 26;
  }
  return parts.join('');
}

function panel(top, title, xLabel, costFn, crossover, xTicks, xMax) {
  const ML = 66;
  const MR = 26;
  const MT = 46;
  const MB = 54;
  const plotL = ML;
  const plotR = W - MR;
  const plotT = top + MT;
  const plotB = top + PANEL_H - MB;
  const plotW = plotR - plotL;
  const plotH = plotB - plotT;

  const yMax = Y_MAX;
  const yTicks = Y_TICKS;
  const px = (x) => plotL + (x / xMax) * plotW;
  const py = (v) => plotB - (Math.min(v, yMax) / yMax) * plotH;

  const N = 80;
  const pts = [];
  for (let i = 0; i <= N; i++) {
    const x = (i / N) * xMax;
    pts.push(`${px(x).toFixed(1)},${py(costFn(x)).toFixed(1)}`);
  }
  const crX = px(crossover);
  const redisY = py(REDIS);

  const out = [`<g>`];
  out.push(
    `<text x="${ML}" y="${top + 26}" font-size="13.5" font-weight="600" fill="${COL.ink}">${title}</text>`,
  );
  // win / lose bands
  out.push(
    `<rect x="${plotL}" y="${plotT}" width="${(crX - plotL).toFixed(1)}" height="${plotH}" fill="${COL.win}" opacity="0.06"/>`,
    `<rect x="${crX.toFixed(1)}" y="${plotT}" width="${(plotR - crX).toFixed(1)}" height="${plotH}" fill="${COL.redis}" opacity="0.06"/>`,
    `<text x="${(plotL + (crX - plotL) / 2).toFixed(1)}" y="${plotT + 18}" font-size="11" fill="${COL.win}" text-anchor="middle" font-weight="600">cheaper than Redis</text>`,
    `<text x="${(crX + (plotR - crX) / 2).toFixed(1)}" y="${plotT + 18}" font-size="11" fill="${COL.inkSoft}" text-anchor="middle" font-weight="600">Redis is cheaper</text>`,
  );
  // y grid + labels
  for (const t of yTicks) {
    const y = py(t);
    out.push(
      `<line x1="${plotL}" y1="${y.toFixed(1)}" x2="${plotR}" y2="${y.toFixed(1)}" stroke="${COL.hair}" stroke-width="1"/>`,
      `<text x="${plotL - 10}" y="${(y + 4).toFixed(1)}" font-size="11" fill="${COL.muted}" text-anchor="end">$${t}</text>`,
    );
  }
  // x labels
  for (const t of xTicks) {
    out.push(
      `<text x="${px(t).toFixed(1)}" y="${plotB + 20}" font-size="11" fill="${COL.muted}" text-anchor="middle">${t}</text>`,
    );
  }
  out.push(
    `<text x="${((plotL + plotR) / 2).toFixed(1)}" y="${plotB + 42}" font-size="12" fill="${COL.inkSoft}" text-anchor="middle">${xLabel}</text>`,
  );
  // redis flat line
  out.push(
    `<line x1="${plotL}" y1="${redisY.toFixed(1)}" x2="${plotR}" y2="${redisY.toFixed(1)}" stroke="${COL.redis}" stroke-width="2" stroke-dasharray="6 4"/>`,
  );
  // CloudBitmaps curve
  out.push(
    `<polyline points="${pts.join(' ')}" fill="none" stroke="${COL.cr}" stroke-width="2.5"/>`,
  );
  // crossover marker
  out.push(
    `<line x1="${crX.toFixed(1)}" y1="${plotT}" x2="${crX.toFixed(1)}" y2="${plotB}" stroke="${COL.muted}" stroke-width="1" stroke-dasharray="3 3"/>`,
    `<circle cx="${crX.toFixed(1)}" cy="${redisY.toFixed(1)}" r="4.5" fill="${COL.cr}"/>`,
    // BELOW the baseline, not above it. The curve crosses the flat Redis line exactly here by definition, so
    // a label at `redisY - 10` is guaranteed to be printed over the curve's own stroke — which it was, most
    // illegibly. Below-right of the crossing is the one quadrant the curve has just left.
    `<text x="${(crX + 8).toFixed(1)}" y="${(redisY + 20).toFixed(1)}" font-size="12" font-weight="700" fill="${COL.cr}">crossover ≈ ${crossover.toFixed(crossover < 100 ? 1 : 0)} /s</text>`,
  );
  out.push(`</g>`);
  return out.join('\n');
}

// ── Stats tables ─────────────────────────────────────────────────────────────────────────────────
const rows = [
  [
    'At-rest (1.2 GiB, no traffic)',
    `$${results.atRest.monthlyUSD.toFixed(2)}/mo`,
    `${results.atRest.pctOfRedis}% of the $${REDIS} cluster`,
    esc(results.atRest.verdict),
  ],
  [
    'Read crossover',
    `${results.readCrossoverPerSec} reads/s`,
    'object GETs, cache off',
    'past here the cluster is cheaper',
  ],
  [
    'Redis-HA baseline',
    `$${REDIS}/mo`,
    'one cluster, whatever the data size',
    'the comparison line',
  ],
  [
    'The Redis the default prices for the 1.2 GiB set',
    `$${results.referenceRedis.monthlyUSD.toFixed(2)}/mo`,
    `${results.referenceRedis.cluster}, the cheapest cluster in the catalogue that holds it`,
    `the line would sit at ${results.referenceRedis.readCrossoverPerSec.toFixed(2)} reads/s`,
  ],
];
// NOTE — there is deliberately no HTML table here any more. site/benchmarks.html hand-writes its own
// "Cost anchors" panel, which is a superset of the first three rows (it adds segment publishes and the A ∩ B
// chunk-skipping row) in the site's own .tpanel form with verdict chips and a basis column. Injecting this
// table beside it would print three of those numbers twice in two different styles. The site's copies are
// instead verified against bench/results.json by scripts/site-figures.cjs, in BOTH directions — every anchor
// must appear, and no money figure may appear that no source accounts for. The markdown table below is still
// injected, because docs/benchmarks.md has no hand-written equivalent.
const mdTable =
  `| Scenario | Value | Basis | Verdict |\n| --- | --- | --- | --- |\n` +
  rows.map((r) => `| ${r[0]} | **${r[1]}** | ${r[2]} | ${r[3]} |`).join('\n');

// ── Write / inject ───────────────────────────────────────────────────────────────────────────────
write('bench/crossover.svg', `<?xml version="1.0" encoding="UTF-8"?>\n${svg}\n`);
write('bench/results.json', JSON.stringify(results, null, 2) + '\n');
// The site takes the svg inline (so it inherits the page's theme tokens); the docs take it as an <img> and
// carry the stats table the site hand-writes. Only the regions passed are touched, so a file is not required
// to host every marker pair — but a marker pair that IS named must exist, or replaceRegion throws.
inject('site/benchmarks.html', { CHART: svg });
inject('docs/benchmarks.md', {
  CHART: `![CloudBitmaps against one Redis-HA cluster: where the cost crosses](../bench/crossover.svg)`,
  STATS: mdTable,
});

function inject(rel, regions) {
  // Line endings are not content: a checkout that turns them into CRLF must not fail the check.
  let s = fs.readFileSync(path.join(ROOT, rel), 'utf8').replace(/\r\n/g, '\n');
  for (const [name, body] of Object.entries(regions)) s = replaceRegion(s, name, body, rel);
  put(rel, s);
}
function replaceRegion(s, name, body, rel) {
  const start = `<!-- BENCH:${name}:START -->`;
  const end = `<!-- BENCH:${name}:END -->`;
  const i = s.indexOf(start);
  const j = s.indexOf(end);
  // Throwing rather than warning is deliberate: a silently-skipped region publishes a page with a stale or
  // empty figure, which is worse than a failed run. This is exactly how the site rebuild broke `pnpm bench` —
  // the markers were dropped with the old markup and nothing noticed until the next run.
  if (i === -1 || j === -1) throw new Error(`missing BENCH:${name} markers in ${rel}`);
  return s.slice(0, i + start.length) + '\n' + body + '\n' + s.slice(j);
}
function write(rel, body) {
  put(rel, body);
}
/** Write a file, or under `--check` compare it with what is on disk and remember it if they differ. */
function put(rel, body) {
  const file = path.join(ROOT, rel);
  if (check) {
    const now = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null;
    if (now !== body) stale.push(rel);
    return;
  }
  fs.writeFileSync(file, body);
  log(rel);
}
function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function round(n, d) {
  const f = 10 ** d;
  return Math.round(n * f) / f;
}
function log(rel) {
  console.log(`  wrote ${rel}`);
}

if (check) {
  if (stale.length > 0) {
    console.error(
      `bench:check: ${stale.join(', ')} ${stale.length === 1 ? 'is' : 'are'} not what the shipped estimator gives. ` +
        'Run `pnpm bench` rather than editing them by hand.',
    );
    process.exit(1);
  }
  console.log(
    'bench:check: bench/crossover.svg, bench/results.json and the BENCH regions of site/benchmarks.html and ' +
      'docs/benchmarks.md are current.',
  );
} else {
  console.log(
    `bench: readCross=${results.readCrossoverPerSec}/s atRest=$${results.atRest.monthlyUSD}/mo (${results.atRest.pctOfRedis}% of the $${REDIS} cluster, ${results.atRest.verdict})`,
  );
}
