#!/usr/bin/env node
/**
 * Gates the cost anchors on `site/benchmarks.html` against their sources.
 *
 * WHY THIS SCRIPT EXISTS
 *
 * The designed benchmarks page carried the line "Every anchor on this page is asserted in CI, so a regression
 * or an overclaim breaks the build." That was not true — nothing asserted them. It is the worst available kind
 * of overclaim, because it is a claim about our own rigour printed on the one page whose entire purpose is
 * that we do not make claims like that.
 *
 * The options were to delete the sentence or to make it true. This makes it true.
 *
 * WHAT IS CHECKED
 *
 *   1. Every anchor value appears on the page, in the rendered form a reader sees.
 *   2. No unaccounted money figure or crossover rate appears anywhere in the page's visible text — the
 *      inverse direction, without which a check can only catch a MISSING number and never a WRONG one added
 *      beside the right ones. (That hole was real: an earlier version of the /demo gate passed while the page
 *      said 41,208 instead of 100,000, because 100,000 still appeared elsewhere.)
 *
 * SOURCES, and neither is hand-maintained:
 *   · bench/results.json      — generated by `pnpm bench` from the shipped estimateCost().
 *   · docs/benchmarks.md      — the unit-economics table, parsed rather than transcribed.
 *
 * Usage: node scripts/site-figures.cjs        (report + exit non-zero on any mismatch)
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const RESULTS = path.join(ROOT, 'bench', 'results.json');
const DOC = path.join(ROOT, 'docs', 'benchmarks.md');

const problems = [];
const fail = (m) => problems.push(m);

const results = JSON.parse(fs.readFileSync(RESULTS, 'utf8'));
const doc = fs.readFileSync(DOC, 'utf8');

// ── the three unit-economics anchors, parsed out of the docs table ────────────────────────────────────────
function docAnchor(label) {
  const re = new RegExp(
    `\\|[^|\\n]*${label}[^|\\n]*\\|\\s*\\*\\*\\$([\\d.]+) per million\\*\\*`,
    'i',
  );
  const m = re.exec(doc);
  if (!m) {
    fail(`docs/benchmarks.md no longer states a "per million" cost for ${label}`);
    return null;
  }
  return Number(m[1]);
}
const writeCost = docAnchor('Incremental');
const countCost = docAnchor('count\\(\\)');
const publishCost = docAnchor('Segment publish');

// ── the latency claim, also parsed ────────────────────────────────────────────────────────────────────────
const p50 = /\*\*p50\*\*\s*\|\s*\*\*([\d.]+) ms\*\*/.exec(doc);
const p99 = /\|\s*p99\s*\|\s*\*\*([\d.]+) ms\*\*/.exec(doc);
if (!p50 || !p99) fail('docs/benchmarks.md no longer states the p50/p99 warm has() figures');

// ── the estimator's own accuracy (K3) ─────────────────────────────────────────────────────────────────────
// This is the claim every other figure on the page rests on, since they all come out of estimateCost(). Parsed
// rather than transcribed so that loosening it in the docs cannot leave a tighter number published on the site.
const k3 = /prediction lands within ±(\d+)% of the engine's actual measured/.exec(doc);
if (!k3) fail("docs/benchmarks.md no longer states the estimator's ±N% accuracy claim (K3)");

// ── the real-cloud calibration receipt ────────────────────────────────────────────────────────────────────
// The only figures on the page that are what AWS ACTUALLY CHARGED rather than what the model predicts, so they
// are also the only ones a reader has no way to sanity-check. Every line item, the total, the request count,
// the date and the run id come out of the docs table. Transcribing a receipt by hand is exactly how a page ends
// up quoting a number no run produced.
const calDate = /MEASURED\*\* against real S3 \+ DynamoDB on \*\*(\d{4}-\d{2}-\d{2})\*\*/.exec(doc);
const calRun = /run id `([\w-]+)`/.exec(doc);
if (!calDate || !calRun)
  fail('docs/benchmarks.md no longer dates/identifies the AWS calibration run');

// Line items: `| DynamoDB write | 2,020 WRU | $0.625/M | $0.001263 |` and the bolded Total row.
const calRows = [
  ...doc.matchAll(
    /^\|\s*(?:\*\*)?([\w /]+?)(?:\*\*)?\s*\|\s*(?:\*\*)?([\d,]+(?: \w+)?)(?:\*\*)?\s*\|[^|\n]*\|\s*(?:\*\*)?(\$[\d.]+)(?:\*\*)?\s*\|$/gm,
  ),
]
  .map((m) => ({ term: m[1].trim(), qty: m[2].trim(), cost: m[3] }))
  .filter((r) => /Dynamo|S3|Total/i.test(r.term));
if (calRows.length < 5) {
  fail(
    `docs/benchmarks.md's calibration table parsed to ${calRows.length} rows, expected 5 ` +
      '(4 line items + total) — did its shape change?',
  );
}

// ── the reserved-RAM baseline's SPEC ──────────────────────────────────────────────────────────────────────
// $346 appeared eight times across the site without ever saying what it buys, which made the single most
// load-bearing comparison on the page unauditable: a reader could not tell whether the node was sized for this
// dataset or several times larger than it. The spec is now published, so it gets gated like every other claim.
//
// Source is the pricing profile's own trailing comment in core/cost.ts — the same literal the $346 comes from,
// so the prose cannot drift from the number it describes. Parsed, not transcribed.
const COST = path.join(ROOT, 'packages', 'core', 'src', 'core', 'cost.ts');
const baseline =
  /redis:\s*\{\s*monthlyUSD:\s*(\d+)\s*\}\s*,?\s*\/\/\s*ElastiCache HA:\s*([^;]+);\s*~\$(\d+) single-node/.exec(
    fs.readFileSync(COST, 'utf8'),
  );
if (!baseline) {
  fail(
    'core/cost.ts no longer states the Redis baseline in the expected "ElastiCache HA: <topology>; ~$N single-node" form',
  );
} else if (Number(baseline[1]) !== results.redisBaselineUSD) {
  fail(
    `core/cost.ts says $${baseline[1]}/mo but bench/results.json says $${results.redisBaselineUSD} — re-run \`pnpm bench\``,
  );
}
// e.g. "1 primary + 2 replicas (cache.m7g.large)" -> the node count and the instance class must both be on the page.
const baselineTopology = baseline ? baseline[2].replace(/\s*\([^)]*\)\s*$/, '').trim() : null;
const baselineInstance = baseline ? /\(([\w.]+)\)/.exec(baseline[2])?.[1] : null;

// ── at-rest rounds for display, and the rounding is stated rather than assumed ─────────────────────────────
const atRestExact = results.atRest.monthlyUSD; // 0.0276
const atRestShown = atRestExact.toFixed(2); // "0.03"
if (Number(atRestShown) === 0) fail(`atRest.monthlyUSD (${atRestExact}) rounds to $0.00 at 2dp`);

const anchors = [
  ['1M incremental writes', writeCost === null ? null : `$${writeCost.toFixed(2)}`],
  ['1M count() calls', countCost === null ? null : `$${countCost.toFixed(2)}`],
  ['1M segment publishes', publishCost === null ? null : `$${publishCost.toFixed(2)}`],
  ['at rest, monthly', `$${atRestShown}`],
  ['at rest, size', `${results.atRest.sizeGiB} GiB`],
  ['at rest, % of Redis', `${results.atRest.pctOfRedis}%`],
  ['Redis-HA baseline', `$${results.redisBaselineUSD}`],
  ['write crossover', `${results.writeCrossoverPerSec}`],
  ['read crossover', `${results.readCrossoverPerSec}`],
  ['item size assumption', `${results.assumptions.avgItemKiB} KiB`],
  ['warm has() p50', p50 ? `${p50[1]} ms` : null],
  ['warm has() p99', p99 ? `${p99[1]} ms` : null],
  ['estimator accuracy (K3)', k3 ? `±${k3[1]}%` : null],
  ['baseline topology', baselineTopology],
  ['baseline instance class', baselineInstance],
  ['baseline single-node', baseline ? `$${baseline[3]}` : null],
  ['calibration date', calDate ? calDate[1] : null],
  ['calibration run id', calRun ? calRun[1] : null],
  // Every calibration line item and the total, so the receipt cannot be quietly retyped.
  //
  // Quantities are only anchored when they are DISCRIMINATING — `2,020 WRU`, `6,355 requests`. The S3 rows'
  // quantities are the bare strings "22" and "23", which `includes()` would find in almost any page (a year, a
  // percentage, a pixel value), so anchoring them would add two checks that cannot fail. A gate that always
  // passes is worse than no gate, because it reports coverage it does not have. The cost column carries those
  // two rows instead, and every cost is distinctive to six decimal places.
  ...calRows.flatMap((r) => [
    ...(/[ ,]/.test(r.qty) ? [[`calibration · ${r.term} qty`, r.qty]] : []),
    [`calibration · ${r.term} cost`, r.cost],
  ]),
];

// ── the inverse check now covers HOME as well as /benchmarks ───────────────────────────────────────────────
// The rebuilt home page states, in its own words, that "every money figure and rate on this site is checked in
// CI against the sources that produced it — in both directions". That was FALSE the moment it was written: this
// script only ever read benchmarks.html, and Home quotes eight money figures of its own.
//
// A page claiming our rigour while nothing enforces it is the specific failure this script was created to fix
// (the designed benchmarks page said its anchors were CI-asserted when nothing asserted them). Shipping the same
// error again, on the home page, would be worse than the first time. So the claim is made true instead.
//
// Home is checked for the INVERSE direction only. It is a summary: it is expected to quote a subset, and
// requiring every anchor to appear on it would force the estimator's p50, the calibration run id and the
// crossover topologies onto a page whose job is not to carry them. What must never happen is Home stating a
// figure no source accounts for.
const PAGES = [
  { rel: 'site/benchmarks.html', requireAll: true },
  { rel: 'site/index.html', requireAll: false },
];

for (const page of PAGES) {
  const PAGE_PATH = path.join(ROOT, page.rel);
  let html;
  try {
    html = fs.readFileSync(PAGE_PATH, 'utf8');
  } catch {
    fail(`${page.rel} is missing`);
  }
  if (!html) continue;
  // The inlined crossover chart is stripped out before the prose scan, and then checked separately below.
  //
  // Why: its y-axis ticks are $0/$200/$400/$600 and its curve labels restate the crossovers, so leaving it in
  // made the inverse check fire on four axis labels. Whitelisting those four strings would have been the wrong
  // fix — it widens the allow-list permanently to silence a specific run, and a later Y_MAX change would then
  // introduce new unaccounted figures OR silently pass. The chart is not prose: bench/run.cjs generates it from
  // the same bench/results.json this script reads, so it cannot drift from the anchors independently. What it
  // CAN do is disagree about the crossover it marks, so that is asserted directly.
  const svgs = html.match(/<svg[\s\S]*?<\/svg>/g) || [];

  // Meta descriptions are pulled into the scan explicitly. Stripping tags removes attribute VALUES, so
  // every money figure inside <meta name="description" content="..."> was invisible to the check below —
  // and those strings are the copy a search result and a shared link actually show, which makes them the
  // highest-leverage sentences on the site rather than the lowest. Home currently quotes $0.03 and $346 in
  // three of them.
  const metas = [
    ...html.matchAll(
      /<meta[^>]*(?:name="(?:description|twitter:description)"|property="og:description")[^>]*content="([^"]*)"/g,
    ),
  ]
    .map((m) => m[1])
    .join(' ');

  const visible = html
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/g, '')
    .replace(/<svg[\s\S]*?<\/svg>/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .concat(' ', metas);

  // ── the chart, checked rather than exempted ──────────────────────────────────────────────────────────
  // Mirrors bench/run.cjs's own rounding: one decimal below 100/s, none above.
  const chartLabel = (n) => `crossover ≈ ${n.toFixed(n < 100 ? 1 : 0)} /s`;
  const chart = svgs.find((s) => s.includes('crossover'));
  if (page.requireAll && !chart) {
    fail(
      'benchmarks.html no longer inlines the crossover chart — run `pnpm bench` to refill BENCH:CHART',
    );
  } else if (chart) {
    for (const [what, want] of [
      ['the write crossover', chartLabel(results.writeCrossoverPerSec)],
      ['the read crossover', chartLabel(results.readCrossoverPerSec)],
      ['the Redis baseline', `$${results.redisBaselineUSD}/mo`],
    ]) {
      if (!chart.includes(want)) {
        fail(`the inlined chart does not mark ${what} (${want}) — stale? re-run \`pnpm bench\``);
      }
    }
  }

  // 1 · every anchor must be stated — on /benchmarks, which is the page that owns them
  if (page.requireAll) {
    for (const [name, want] of anchors) {
      if (want === null) continue;
      if (!visible.includes(want)) fail(`${page.rel} never states ${name} (${want})`);
    }
  }

  // 2 · and nothing else that looks like money or a rate may appear
  const allowed = new Set(anchors.map(([, v]) => v).filter(Boolean));
  // The page legitimately restates figures owned by other pages' gates; each is listed so that adding one is
  // a deliberate act rather than a silent widening.
  const alsoAllowed = new Set([
    '$0.03', // at-rest, the rounded form
    '100', // chunks fetched — gated by site-replay.cjs
    '2,000', // chunks per segment — same
    '25.3 ms', // intersect wall time — same
    '1,900', // chunks skipped per segment — same
    // Home only. "$0" is the standing charge — the ABSENCE of a charge, which is the whole pitch of layer 03.
    // There is no source that could "account for" zero, and demanding one would be the check misfiring on the
    // one figure that needs no evidence.
    '$0',
  ]);
  const money = visible.match(/\$[\d,]+(?:\.\d+)?/g) || [];
  for (const m of new Set(money)) {
    if (!allowed.has(m) && !alsoAllowed.has(m)) {
      fail(`${page.rel} states ${m}, which no source accounts for`);
    }
  }
}

if (problems.length) {
  console.error('site-figures: benchmarks.html disagrees with its sources:');
  for (const p of problems) console.error(`  - ${p}`);
  console.error(
    '\n  Sources: bench/results.json (regenerate with `pnpm bench`) · docs/benchmarks.md',
  );
  process.exit(1);
}

console.log(
  `site-figures: ${anchors.filter(([, v]) => v).length} anchors verified against their sources.`,
);
for (const [name, v] of anchors) if (v) console.log(`  ${name.padEnd(24)} ${v}`);
