#!/usr/bin/env node
/**
 * Gates the published figures on the site's pages — the `PAGES` list below: six site pages, `llms.txt`, the two
 * READMEs, the roadmap and `docs/benchmarks.md`, which quote the same figures — against their sources.
 *
 * WHY THIS SCRIPT EXISTS
 *
 * The designed benchmarks page carried the line "Every anchor on this page is asserted in CI, so a regression
 * or an overclaim breaks the build." That was not true — nothing asserted them. It is the worst available kind
 * of overclaim, because it is a claim about our own rigour printed on the one page whose entire purpose is
 * that we do not make claims like that.
 *
 * The options were to delete the sentence or to make it true. This makes it true.
 *
 * WHAT IS CHECKED
 *
 *   1. Every anchor value appears on the page, in the rendered form a reader sees.
 *   2. No unaccounted DOLLAR figure appears anywhere in the page's visible text — the inverse direction,
 *      without which a check can only catch a MISSING number and never a WRONG one added beside the right ones.
 *      Across a whole page only `$` amounts are matched: a crossover rate is required on the page that owns it
 *      (1), but a wrong rate stated on another page is not caught here. (That hole was real: an earlier version
 *      of the /demo gate passed while the page said 41,208 instead of 100,000, because 100,000 still appeared
 *      elsewhere.) Wherever a page quotes the latest calibration run — a paragraph, list item or table row that
 *      names the run or states one of its headline figures — every unit is matched there, rates and counts
 *      included, through the matcher the run's report is held to, and so are the rows of the benchmarks page's
 *      panel on the run, one by one.
 *   3. The counts in Home's spec strip, derived from the source tree — checked in three directions: the page
 *      drifting from the source, the source drifting from the page, and the entry being deleted outright.
 *
 * SOURCES, and none is hand-maintained:
 *   · bench/results.json      — generated by `pnpm bench` from the shipped estimateCost().
 *   · bench/calibration/*.json — the real-cloud calibration runs, as their harness wrote them. The latest one's
 *     figures are derived by bench/lib/calibration-figures.cjs, the same code that holds the run's report to it.
 *   · bench/rss-gate-results.json — generated by `pnpm rss-gate`: the hard cgroup ceiling a sustained
 *     workload survived, plus the soak verdict from that run.
 *   · docs/benchmarks.md      — the unit-economics table, parsed rather than transcribed.
 *   · every package's src    — the driver classes themselves, for the backend count.
 *   · packages/roaring/…json  — its declared dependencies, for the third-party count.
 *
 * Usage: node scripts/site-figures.cjs        (report + exit non-zero on any mismatch)
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const RESULTS = path.join(ROOT, 'bench', 'results.json');
const DOC = path.join(ROOT, 'docs', 'benchmarks.md');
const SITE = path.join(ROOT, 'site');

const problems = [];
const fail = (m) => problems.push(m);

const results = JSON.parse(fs.readFileSync(RESULTS, 'utf8'));
const doc = fs.readFileSync(DOC, 'utf8');

/** The part of `text` under the first heading `heading` matches, down to the next heading at its level or above. */
function sectionOf(text, heading) {
  const lines = text.split('\n');
  const at = lines.findIndex((l) => heading.test(l));
  if (at === -1) return null;
  const level = /^#+/.exec(lines[at])[0].length;
  const end = lines.findIndex(
    (l, i) => i > at && /^#+ /.test(l) && /^#+/.exec(l)[0].length <= level,
  );
  return lines.slice(at, end === -1 ? undefined : end).join('\n');
}

// The July receipt is parsed out of ITS OWN section. The page now reports two runs, and the parsers below took the
// first match in the whole document — so the newer run's section, written above it, would have been read as the
// July receipt the moment it used the same phrasing.
const july = sectionOf(doc, /^#{2,4} The July 2026 run/) ?? '';
if (july === '') fail('docs/benchmarks.md no longer has its "The July 2026 run" section');

// ── the three unit-economics anchors, parsed out of the docs table ────────────────────────────────────────
function docAnchor(label) {
  const re = new RegExp(
    `\\|[^|\\n]*${label}[^|\\n]*\\|\\s*\\*\\*\\$([\\d.]+) per million\\*\\*`,
    'i',
  );
  const m = re.exec(july);
  if (!m) {
    fail(`docs/benchmarks.md no longer states a "per million" cost for ${label}`);
    return null;
  }
  return Number(m[1]);
}
// There is no per-id write line any more, and there must not be one: data enters a segment only as a whole
// generation, so the two operations a reader can be billed for are a read and a publish.
const countCost = docAnchor('count\\(\\)');
const publishCost = docAnchor('Segment publish');
if (/\|[^|\n]*[Ii]ncremental[^|\n]*\|\s*\*\*\$[\d.]+ per million/.test(doc)) {
  fail(
    'docs/benchmarks.md prices an "incremental write" per million — there is no per-id write path; a set ' +
      'changes by publishing a new generation, so that row would price an operation the library cannot perform',
  );
}

// ── latency: deliberately unpublished, and that has to be enforced rather than trusted ────────────────────
// The p50/p99 figures this gate used to parse came from a run that metered a delta tier the library no longer
// has, so they are gone from the page. What replaces them is not a looser check but an INVERSE one: the page
// must not publish a millisecond latency for a read verb until an in-region run measures one. Without this,
// re-quoting the old numbers is a docs edit that CI would wave through.
const strayLatency = /\|\s*(?:\*\*)?p(?:50|95|99)(?:\*\*)?\s*\|/.exec(doc);
if (strayLatency) {
  fail(
    'docs/benchmarks.md states a p50/p95/p99 latency row — in-region read latency is listed as owed, not ' +
      'measured (see "What is still owed"); publishing one needs a run behind it',
  );
}

// ── the estimator's own accuracy ───────────────────────────────────────────────────────────────────────────
// The claim the MODELLED figures on the page rest on, since they come out of estimateCost(). It used to be a
// tolerance ("within ±N%") and is now a DIRECTION: priced against the chunk GETs a metrics sink actually observed,
// the prediction must land on or above the measured cost. The direction is the stronger claim — a tolerance
// permits an under-quote of N%, and an estimator that under-quotes your bill is the one failure mode that matters.
//
// It is also a NARROW claim, and the page has to say so. It used to read "never quotes a cheaper bill than the
// engine incurs", which the single-bucket calibration run showed to be false as a claim about a bill: the
// estimator then had no term for the pointer's requests or an intersect's tail reads. It counts those now, held to
// the engine's request counts by tests/core/cost.test.ts, but "a cheaper bill" is still false: an intersect that
// outlives the pointer TTL re-reads its pointers, which that run did from outside the region, and a load that
// loses a publish race reads the pointer again. What the anchor test proves is chunk reads on an in-memory store,
// so what is gated is that the page states it as a floor, and scopes it to chunk reads.
if (!/never quotes fewer chunk reads than the engine makes/.test(doc)) {
  fail(
    'docs/benchmarks.md no longer states the estimator\'s no-under-quote claim ("never quotes fewer chunk ' +
      'reads than the engine makes")',
  );
}
if (/never quotes a cheaper bill/.test(doc)) {
  fail(
    'docs/benchmarks.md claims the estimator "never quotes a cheaper bill" — it under-quotes a single-bucket ' +
      'intersect that outlives the pointer TTL, or a load that loses a publish race; the anchor test proves chunk ' +
      'reads only',
  );
}
if (/prediction lands within ±\d+%/.test(doc)) {
  fail(
    'docs/benchmarks.md states the estimator accuracy as a ±N% band, but the claim is a floor (never cheaper than ' +
      'measured), and a band would publish a weaker claim than the test makes',
  );
}

// ── the real-cloud calibration receipt ────────────────────────────────────────────────────────────────────
// The July run's receipt: list prices over the requests that run metered, rather than what the model predicts —
// which makes it, with the single-bucket run below, one of the only figures a reader has no way to sanity-check. Every line item, the total, the request count,
// the date and the run id come out of the docs table. Transcribing a receipt by hand is exactly how a page ends
// up quoting a number no run produced.
const calDate = /MEASURED\*\* against real S3[^*]*on \*\*(\d{4}-\d{2}-\d{2})\*\*/.exec(july);
const calRun = /run id `([\w-]+)`/.exec(july);
if (!calDate || !calRun)
  fail('docs/benchmarks.md no longer dates/identifies the AWS calibration run');

// Line items: `| S3 GET | 23 | $0.40/M | $0.000009 |` and the bolded Total row. The `Dynamo` term is still
// matched below so a re-added NoSQL line item is caught, not quietly published — the driver is gone, but the
// half-run those figures came from is still the source this page transcribes.
const calRows = [
  ...july.matchAll(
    /^\|\s*(?:\*\*)?([\w /]+?)(?:\*\*)?\s*\|\s*(?:\*\*)?([\d,]+(?: \w+)?)(?:\*\*)?\s*\|[^|\n]*\|\s*(?:\*\*)?(\$[\d.]+)(?:\*\*)?\s*\|$/gm,
  ),
]
  .map((m) => ({ term: m[1].trim(), qty: m[2].trim(), cost: m[3] }))
  .filter((r) => /Dynamo|S3|Total/i.test(r.term));
// Two line items, both S3 — the object-store half of the run. The other half metered a delta tier the library
// no longer has, and its rows are not restated: they would put a price on a code path you cannot take.
if (calRows.length !== 2) {
  fail(
    `docs/benchmarks.md's calibration table parsed to ${calRows.length} rows, expected 2 ` +
      '(the two S3 line items) — did its shape change?',
  );
}
// And no total, checked rather than assumed. A "total" over two terms of four is a number no run produced, so
// the page says so in prose; this makes re-adding one a build failure instead of a plausible-looking edit.
if (calRows.some((r) => /Total/i.test(r.term))) {
  fail(
    "docs/benchmarks.md's calibration table publishes a Total — the run's other half is withheld, so a total " +
      'over the remaining rows would be a figure no run produced',
  );
}
if (calRows.some((r) => /Dynamo/i.test(r.term))) {
  fail(
    "docs/benchmarks.md's calibration table restates a DynamoDB line item — those terms metered the removed " +
      'delta tier; publishing them prices a path the library no longer has',
  );
}

// ── the single-bucket calibration run ─────────────────────────────────────────────────────────────────────
// The bill for the topology that ships: the pointer in the same bucket as the data. Its figures are DERIVED from
// the run's committed evidence by the module that also holds the run's report to it, so the site and the report
// take a run's numbers from one place, and a figure cannot be retyped here without the evidence to back it.
const calibration = require('../bench/lib/calibration-figures.cjs');
const calibrationRuns = calibration.evidenceFiles(ROOT);
let singleBucket = null;
if (calibrationRuns.length === 0) {
  fail(
    'bench/calibration/ holds no run evidence, but the benchmarks page publishes a single-bucket bill',
  );
} else {
  try {
    singleBucket = calibration.derive(
      JSON.parse(fs.readFileSync(path.join(ROOT, calibrationRuns.at(-1)), 'utf8')),
      calibration.readSources(ROOT),
    );
  } catch (err) {
    fail(err.message);
  }
}
/** One of the run's anchors, by the name calibration-figures gives it. A name it no longer has is a failure. */
const singleBucketFigure = (name) => {
  if (singleBucket === null) return null;
  const found = singleBucket.anchors.find(([n]) => n === name);
  if (found === undefined)
    fail(`bench/lib/calibration-figures.cjs derives no figure named "${name}"`);
  return found?.[1] ?? null;
};

// ── every OTHER statement of the driver count, on every page ──────────────────────────────────────────────
// Home's spec strip is anchored above. This catches the same number wherever else it is written: the
// `<p class="meta">` footer that repeats across most pages, and the spelled-out form in prose, headings, nav
// buttons and `<meta>` description tags — which is where it actually went stale, and which a digit-only check
// cannot see. Spelled-out numbers are checked one past the true count in both directions, so this keeps working
// when a driver is added or removed rather than pinning today's answer.
const NUMBER_WORDS = [
  'zero',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
];
/**
 * Reader-visible text: tags become a space, entities are decoded, whitespace collapses.
 *
 * Every prose rule below runs on THIS, never on raw markup. Matching a prose pattern against serialised HTML
 * looked equivalent and was not: `<strong>9</strong> storage drivers` reads as a count to a human and matched
 * nothing, because the regex wanted literal whitespace between the number and the noun — and wrapping a figure
 * in `<strong>` is this site's own house style, so the markup the pages already use was the bypass. An
 * adversarial review put a wrong driver count and a wrong dependency count on the page that way, and the only
 * trace was a statement tally quietly dropping by one.
 *
 * Comments are KEPT deliberately. `view-source` is public, and a stale claim in a comment is exactly the kind
 * that nothing re-reads.
 */
function visibleText(html) {
  // `<meta name="description">` and `og:description` FIRST. Their text is reader-facing — it is what a search
  // result and a shared link show — but it lives in an attribute, so stripping tags deletes it. Hoisting it
  // into the body keeps it in scope; dropping it silently cost three of the thirteen driver-count statements
  // the moment this function was introduced, which is the kind of coverage loss a passing gate hides.
  const described = [...html.matchAll(/<meta\b[^>]*content="([^"]*)"[^>]*>/gi)]
    .filter((m) => /name="(description|og:description)"|property="og:description"/i.test(m[0]))
    .map((m) => m[1])
    .join(' ');
  return (described + ' ' + html)
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;|&#160;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/\s+/g, ' ');
}

/** Every page under site/, as a [relative path, reader-visible text] pair. */
function sitePages() {
  return fs
    .readdirSync(SITE, { withFileTypes: true, recursive: true })
    .filter((e) => e.isFile() && /\.(html|txt)$/.test(e.name) && e.name !== 'robots.txt')
    .map((e) => path.relative(SITE, path.join(e.parentPath ?? e.path, e.name)))
    .map((rel) => [rel, visibleText(fs.readFileSync(path.join(SITE, rel), 'utf8'))]);
}

function checkDriverCountEverywhere(want) {
  const correctWord = NUMBER_WORDS[want];
  let checked = 0;
  // `llms.txt` is in scope too: it is the copy written to be quoted verbatim by an assistant, so an ungated
  // number there is one that gets repeated as fact somewhere we will never see.
  for (const [rel, text] of sitePages()) {
    // A count and the noun, with room for an adjective between them — "nine production storage drivers" is
    // the same claim and used to walk straight past a pattern that demanded they be adjacent.
    //
    // The slot takes ADJECTIVES only. Function words are excluded because they change the sentence from a
    // count of what ships into a reference to some of it — "one of our drivers" counts nothing — and
    // `the two drivers` names one backend's storage and registry halves, which `S3Storage` configures
    // together. Both are true English about different things, so widening to catch them would flag correct
    // prose: the gate people route around.
    const COUNT = `(\\d+|${NUMBER_WORDS.join('|')})`;
    const ADJECTIVES = '(?:(?!of\\b|in\\b|for\\b|to\\b|storage\\b)[a-z-]+\\s+){0,2}';
    for (const m of text.matchAll(
      new RegExp(`(\\bthe\\s+)?\\b${COUNT}\\s+${ADJECTIVES}(storage\\s+)?drivers\\b`, 'gi'),
    )) {
      // "the" excludes the phrase ONLY where the noun is bare. `the two drivers` is anaphoric — it names one
      // backend's storage and registry halves, which `S3Storage` configures together. `the four storage
      // drivers` is a count of what ships, and saying "storage" is what distinguishes them. An unconditional
      // `the` exclusion dropped that one silently, which the floor below is what caught.
      if (m[1] && !m[3]) continue;
      checked++;
      const token = (m[2] ?? '').toLowerCase();
      const stated = /^\d+$/.test(token) ? Number(token) : NUMBER_WORDS.indexOf(token);
      if (stated !== want) {
        fail(
          `site/${rel} says "${m[0].trim()}" but the source has ${want} (${correctWord}) — ` +
            'a spelled-out count drifts exactly like a digit one',
        );
      }
    }
  }
  return checked;
}

// ── the reserved-RAM baseline's SPEC ──────────────────────────────────────────────────────────────────────
// $346 appeared eight times across the site without ever saying what it buys, which made the single most
// load-bearing comparison on the page unauditable: a reader could not tell whether the node was sized for this
// dataset or several times larger than it. The spec is now published, so it gets gated like every other claim.
//
// Source is the one-cluster anchor's own trailing comment in core/cost.ts — the same literal the $346 comes from,
// so the prose cannot drift from the number it describes. Parsed, not transcribed. The site's $346 is that one
// cluster, which the crossover is drawn against; the estimator's default verdict sizes Redis to the data instead.
const COST = path.join(ROOT, 'packages', 'core', 'src', 'core', 'cost.ts');
const baseline =
  /export const ONE_REDIS_HA_CLUSTER\b[^=]*=\s*\{\s*monthlyUSD:\s*(\d+)\s*\};\s*\/\/\s*ElastiCache HA:\s*([^;]+);\s*~\$(\d+) single-node/.exec(
    fs.readFileSync(COST, 'utf8'),
  );
if (!baseline) {
  fail(
    'core/cost.ts no longer states the Redis baseline in the expected "ElastiCache HA: <topology>; ~$N single-node" form',
  );
} else if (Number(baseline[1]) !== results.redisBaselineUSD) {
  fail(
    `core/cost.ts says $${baseline[1]}/mo but bench/results.json says $${results.redisBaselineUSD} — re-run \`pnpm bench\``,
  );
}
// e.g. "1 primary + 2 replicas (cache.m7g.large)" -> the node count and the instance class must both be on the page.
const baselineTopology = baseline ? baseline[2].replace(/\s*\([^)]*\)\s*$/, '').trim() : null;
const baselineInstance = baseline ? /\(([\w.]+)\)/.exec(baseline[2])?.[1] : null;

// ── at-rest rounds for display, and the rounding is stated rather than assumed ─────────────────────────────
const atRestExact = results.atRest.monthlyUSD; // 0.0276
const atRestShown = atRestExact.toFixed(2); // "0.03"
if (Number(atRestShown) === 0) fail(`atRest.monthlyUSD (${atRestExact}) rounds to $0.00 at 2dp`);

const anchors = [
  // The July run's two unit figures, both without the pointer. The publish one is kept as that run's record; the
  // single-bucket run below measured the pointer too, and its load figure is the one the cost tables now quote.
  ['July · 1M count() calls', countCost === null ? null : `$${countCost.toFixed(2)}`],
  // Superseded, so it may appear only where the page says so: the July receipt, on the benchmarks page and in the
  // doc it is parsed from. Anywhere else it would be quoted as the cost of a publish, which it no longer is.
  [
    'July · 1M segment publishes',
    publishCost === null ? null : `$${publishCost.toFixed(2)}`,
    { onlyOn: ['site/benchmarks.html', 'docs/benchmarks.md'] },
  ],
  ['at rest, monthly', `$${atRestShown}`],
  ['at rest, size', `${results.atRest.sizeGiB} GiB`],
  ['at rest, % of Redis', `${results.atRest.pctOfRedis}%`],
  ['Redis-HA baseline', `$${results.redisBaselineUSD}`],
  // One crossover, because there is one metered axis: reads against a standing node. The write side is not a
  // rate any more — a publish is per-object, so `estimateCost` takes `loadsPerMonth` of them and a
  // "writes per second" figure would describe an operation nobody performs.
  ['read crossover', `${results.readCrossoverPerSec}`],
  ['baseline topology', baselineTopology],
  ['baseline instance class', baselineInstance],
  ['baseline single-node', baseline ? `$${baseline[3]}` : null],
  ['calibration date', calDate ? calDate[1] : null],
  ['calibration run id', calRun ? calRun[1] : null],
  // Every calibration line item and the total, so the receipt cannot be quietly retyped.
  //
  // Quantities are only anchored when they are DISCRIMINATING — `2,020 WRU`, `6,355 requests`. The S3 rows'
  // quantities are the bare strings "22" and "23", which `includes()` would find in almost any page (a year, a
  // percentage, a pixel value), so anchoring them would add two checks that cannot fail. A gate that always
  // passes is worse than no gate, because it reports coverage it does not have. The cost column carries those
  // two rows instead, and every cost is distinctive to six decimal places.
  ...calRows.flatMap((r) => [
    ...(/[ ,]/.test(r.qty) ? [[`calibration · ${r.term} qty`, r.qty]] : []),
    [`calibration · ${r.term} cost`, r.cost],
  ]),
  // The single-bucket run. Every one is distinctive where it appears, which is what makes it worth anchoring.
  ['single-bucket run id', singleBucketFigure('run id')],
  ['single-bucket · chunks fetched', singleBucketFigure('chunks fetched')],
  [
    'single-bucket · GETs, the median measured',
    singleBucketFigure('GETs the median cold intersect made'),
  ],
  [
    'single-bucket · 1M cold intersects, measured',
    singleBucketFigure('per million cold intersects, measured'),
  ],
  [
    'single-bucket · GETs, each pointer read once',
    singleBucketFigure('GETs a cold intersect makes with each pointer read once'),
  ],
  [
    'single-bucket · 1M cold intersects, each pointer read once',
    singleBucketFigure('per million cold intersects with each pointer read once'),
  ],
  [
    'single-bucket · 1M writes and publishes',
    singleBucketFigure('per million single-part write-and-publishes'),
  ],
  ['single-bucket · 1M multipart', singleBucketFigure('per million multipart write-and-publishes')],
  [
    'single-bucket · 1M first store.load()s',
    singleBucketFigure("per million of a segment's first store.load()"),
  ],
  ['single-bucket · the whole run', singleBucketFigure('the run')],
];

// ── the inverse check now covers HOME as well as /benchmarks ───────────────────────────────────────────────
// The rebuilt home page states, in its own words, that "every money figure and rate on this site is checked in
// CI against the sources that produced it — in both directions". That was FALSE the moment it was written: this
// script only ever read benchmarks.html, and Home quotes eight money figures of its own.
//
// A page claiming our rigour while nothing enforces it is the specific failure this script was created to fix
// (the designed benchmarks page said its anchors were CI-asserted when nothing asserted them). Shipping the same
// error again, on the home page, would be worse than the first time. So the claim is made true instead.
//
// Home is checked for the INVERSE direction only. It is a summary: it is expected to quote a subset, and
// requiring every anchor to appear on it would force the estimator's p50, the calibration run id and the
// crossover topologies onto a page whose job is not to carry them. What must never happen is Home stating a
// figure no source accounts for.
//
// The inverse check covers every page that states money, not just those two. /architecture, /usage and /flavors
// each quote the unit economics and the $346 baseline in their own prose, and none of them was gated — the same
// hole this file exists to close, one directory over. They are `requireAll: false` for the same reason Home is:
// each quotes a deliberate subset, and requiring the full anchor set would force the calibration run id and the
// baseline instance class onto pages whose job is not to carry them.
//
// `llms.txt`, the two READMEs and the roadmap are here for the same reason. `llms.txt` is the copy written to be
// quoted verbatim by an assistant, the root and npm READMEs are the most-read pages the project has, and the roadmap
// quotes the calibration's figures where it says what is measured; each quoted the published cost figures with
// nothing checking them.
const MEASURED_1M = 'per million cold intersects, measured';
const EXPECTED_1M = 'per million cold intersects with each pointer read once';
const WRITE_1M = 'per million single-part write-and-publishes';
const PAGES = [
  // `mustState` names the latest run's figures a page quotes, so that replacing one — a load row that turns into
  // the per-PUT $5 the estimator once quoted — fails even where the replacement is a value some source accounts for.
  { rel: 'site/benchmarks.html', requireAll: true },
  { rel: 'site/index.html', requireAll: false, mustState: [MEASURED_1M, WRITE_1M] },
  { rel: 'site/architecture.html', requireAll: false, mustState: [WRITE_1M] },
  { rel: 'site/usage.html', requireAll: false },
  { rel: 'site/flavors.html', requireAll: false, mustState: [MEASURED_1M, WRITE_1M] },
  { rel: 'site/flavors/roaring.html', requireAll: false },
  { rel: 'site/llms.txt', requireAll: false, mustState: [MEASURED_1M, EXPECTED_1M, WRITE_1M] },
  { rel: 'README.md', requireAll: false, mustState: [MEASURED_1M, EXPECTED_1M, WRITE_1M] },
  {
    rel: 'packages/roaring/README.md',
    requireAll: false,
    mustState: [MEASURED_1M, EXPECTED_1M, WRITE_1M],
  },
  { rel: 'docs/ROADMAP.md', requireAll: false, mustState: [MEASURED_1M, EXPECTED_1M, WRITE_1M] },
  // The source the July receipt is parsed from is a page too: a wrong figure beside the parsed ones would
  // otherwise be the one thing in it nothing reads.
  { rel: 'docs/benchmarks.md', requireAll: false },
];

/**
 * A page's blocks, each one a claim's worth of text: an HTML page's paragraphs, list items, headings, captions and
 * table rows, and its meta descriptions; a markdown or text page's paragraphs, list items and table rows.
 */
function blocksOf(text, isHtml, metas) {
  const body = text.replace(/<!--[\s\S]*?-->/g, '');
  if (!isHtml) {
    return body
      .split(/\n\s*\n/)
      .flatMap((b) => b.split(/\n(?=\s*(?:[-*+]|\d+\.) |\s*\|)/))
      .filter((b) => b.trim() !== '');
  }
  const html = body
    .replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/g, '')
    .replace(/<svg[\s\S]*?<\/svg>/g, ' ');
  return [
    ...html
      .split(/<\/(?:p|li|tr|h[1-6]|figcaption|dd|dt|caption|blockquote)>|<br\s*\/?>/i)
      .map((b) => b.replace(/<[^>]+>/g, ' ')),
    ...metas.split(/\s{2,}/),
  ].filter((b) => b.trim() !== '');
}

/** The latest run's headline figures that mark a block as quoting it: its id, its prices and its counts. */
const RUN_TRIGGERS = [
  'run id',
  'chunks fetched',
  'GETs the median cold intersect made',
  'a cold intersect, measured',
  'per million cold intersects, measured',
  'GETs a cold intersect makes with each pointer read once',
  'per million cold intersects with each pointer read once',
  'per million single-part write-and-publishes',
  'per million multipart write-and-publishes',
  "per million of a segment's first store.load()",
  'the run',
  'cold intersects the Redis line buys a month',
  'loads the Redis line buys a month',
];
// A request shape, "4 PUT-class + 7 GET", is the run's to state: a block that states one is about it, and the shape
// must then be one the run has. The usage page's `store.load()` row carried a shape and none of the run's figures.
const REQUEST_SHAPE = /\d+\s?PUTs?(?:-class)?(?:\s+requests?)?,?\s*(?:\+|and|plus)\s*\d+\s?GETs?/;
function quotesTheRun(block) {
  if (singleBucket === null) return false;
  if (REQUEST_SHAPE.test(calibration.normalize(block))) return true;
  // The run's layout is its own: a block that counts its 1,999 chunks is about it, whatever else it says.
  if (
    calibration.statesFigure(
      block,
      `${singleBucket.chunksPerSegment.toLocaleString('en-US')} chunks`,
    )
  ) {
    return true;
  }
  return RUN_TRIGGERS.some((name) => {
    const figure = singleBucketFigure(name);
    return figure !== null && calibration.statesFigure(block, figure);
  });
}

// Figures that are only honest beside what they leave out. Both July unit figures were billed without the pointer
// — its round trip went to a NoSQL table that no longer ships — so wherever one is stated, the pointer has to be
// named within a sentence or two of it.
const NEEDS_THE_POINTER = ['$0.14', '$5.88'];
const NEAR = 280;

for (const page of PAGES) {
  const PAGE_PATH = path.join(ROOT, page.rel);
  let html;
  try {
    html = fs.readFileSync(PAGE_PATH, 'utf8');
  } catch {
    fail(`${page.rel} is missing`);
  }
  if (!html) continue;
  // The inlined crossover chart is stripped out before the prose scan, and then checked separately below.
  //
  // Why: its y-axis ticks are $0/$200/$400/$600 and its curve labels restate the crossovers, so leaving it in
  // made the inverse check fire on four axis labels. Whitelisting those four strings would have been the wrong
  // fix — it widens the allow-list permanently to silence a specific run, and a later Y_MAX change would then
  // introduce new unaccounted figures OR silently pass. The chart is not prose: bench/run.cjs generates it from
  // the same bench/results.json this script reads, so it cannot drift from the anchors independently. What it
  // CAN do is disagree about the crossover it marks, so that is asserted directly.
  const svgs = html.match(/<svg[\s\S]*?<\/svg>/g) || [];

  // Meta descriptions are pulled into the scan explicitly. Stripping tags removes attribute VALUES, so
  // every money figure inside <meta name="description" content="..."> was invisible to the check below —
  // and those strings are the copy a search result and a shared link actually show, which makes them the
  // highest-leverage sentences on the site rather than the lowest. Home currently quotes $0.03 and $346 in
  // three of them.
  const metas = [
    ...html.matchAll(
      /<meta[^>]*(?:name="(?:description|twitter:description)"|property="og:description")[^>]*content="([^"]*)"/g,
    ),
  ]
    .map((m) => m[1])
    .join(' ');

  // Structured data and a drawing's own labels are published text too; only the generated chart is set aside.
  const jsonLd = [
    ...html.matchAll(/<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g),
  ]
    .map((m) => m[1])
    .join(' ');
  const svgText = svgs
    .filter((svg) => !svg.includes('crossover'))
    .flatMap((svg) => [...svg.matchAll(/<text[^>]*>([^<]*)<\/text>/g)].map((m) => m[1]))
    .join(' ');
  // A markdown or text file is not markup: stripping "tags" there would delete prose such as `<runId>`.
  const isHtml = page.rel.endsWith('.html');
  const withoutComments = html.replace(/<!--[\s\S]*?-->/g, '');
  const visible = isHtml
    ? withoutComments
        .replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/g, '')
        .replace(/<svg[\s\S]*?<\/svg>/g, ' ')
        .replace(/<[^>]+>/g, ' ')
        .replace(/&nbsp;|&#160;/gi, ' ')
        .concat(' ', metas, ' ', jsonLd, ' ', svgText)
    : withoutComments;

  // ── the chart, checked rather than exempted ──────────────────────────────────────────────────────────
  // Mirrors bench/run.cjs's own rounding: one decimal below 100/s, none above.
  const chartLabel = (n) => `crossover ≈ ${n.toFixed(n < 100 ? 1 : 0)} /s`;
  const chart = svgs.find((s) => s.includes('crossover'));
  if (page.requireAll && !chart) {
    fail(
      'benchmarks.html no longer inlines the crossover chart — run `pnpm bench` to refill BENCH:CHART',
    );
  } else if (chart) {
    for (const [what, want] of [
      ['the read crossover', chartLabel(results.readCrossoverPerSec)],
      ['the Redis baseline', `$${results.redisBaselineUSD}/mo`],
    ]) {
      if (!chart.includes(want)) {
        fail(`the inlined chart does not mark ${what} (${want}) — stale? re-run \`pnpm bench\``);
      }
    }
  }

  // 1 · every anchor must be stated — on /benchmarks, which is the page that owns them — and each page's own
  for (const name of page.mustState ?? []) {
    const want = singleBucketFigure(name);
    if (want !== null && !calibration.statesFigure(visible, want)) {
      fail(`${page.rel} no longer states ${name} (${want}), which it quotes from the latest run`);
    }
  }
  if (page.requireAll) {
    for (const [name, want] of anchors) {
      if (want === null) continue;
      if (!visible.includes(want)) fail(`${page.rel} never states ${name} (${want})`);
    }
  }

  // 2 · and nothing else that looks like money may appear
  const allowed = new Set(
    anchors
      .filter(
        ([, v, scope]) => v && (scope?.onlyOn === undefined || scope.onlyOn.includes(page.rel)),
      )
      .map(([, v]) => v),
  );
  // The page legitimately restates figures owned by other gates; each is listed so that adding one is a
  // deliberate act rather than a silent widening.
  const alsoAllowed = new Set([
    '$0.03', // at-rest, the rounded form
    // Home only. "$0" is the standing charge — the ABSENCE of a charge, which is the whole pitch of layer 03.
    // There is no source that could "account for" zero, and demanding one would be the check misfiring on the
    // one figure that needs no evidence.
    ...(page.rel === 'site/index.html' ? ['$0'] : []),
  ]);
  // A figure the latest calibration run accounts for passes at the precision it is written, by the same matcher
  // that holds the run's report to its evidence — `$82` for $82.40 as readily as the full figure. Its latency
  // and upload values are not in this set when the run was driven from outside the region.
  // Bindings aside: which claim a figure makes is judged in its sentence, by the per-block check below.
  const byTheRun = (m) =>
    singleBucket !== null &&
    calibration.unaccounted(m, calibration.unbound(singleBucket.pageValues)).length === 0;
  // Read through the matcher's spellings first: `&#36;8.24` and `$ 8.24` are dollar amounts too, and the entity is
  // the usual way to keep a markdown renderer from reading `$…$` as mathematics.
  const plainText = calibration.normalize(visible);
  const money = (plainText.match(/\$\s?[\d,]+(?:\.\d+)?/g) || []).map((m) => m.replace(/\s/g, ''));
  for (const m of new Set(money)) {
    if (!allowed.has(m) && !alsoAllowed.has(m) && !byTheRun(m)) {
      fail(`${page.rel} states ${m}, which no source accounts for`);
    }
  }

  // 2b · and where the page quotes the latest calibration run, every figure in that paragraph, list item or table
  // row — rates, counts, shares and sizes as well as money — is held to the run, or to this page's other sources,
  // with the words that say which claim each makes (see calibration-figures.cjs).
  if (singleBucket !== null) {
    // The run's own figures come from its values, bindings and all. Only the page's other sources join them, as plain
    // values: the run's anchors, merged in plainly, once let "store.load() costs $11.20 per million" pass on every
    // page here, because a plain value passes whatever words stand beside it.
    const otherSources = anchors
      .filter(
        ([name, v, scope]) =>
          v &&
          !name.startsWith('single-bucket') &&
          (scope?.onlyOn === undefined || scope.onlyOn.includes(page.rel)),
      )
      .map(([, v]) => v);
    const values = calibration.mergeValues(
      singleBucket.pageValues,
      calibration.valuesFromFigures([...otherSources, ...alsoAllowed], {
        perSecond: [results.readCrossoverPerSec],
      }),
    );
    for (const block of blocksOf(html, isHtml, metas)) {
      if (!quotesTheRun(block)) continue;
      for (const figure of calibration.unaccounted(block, values)) {
        fail(
          `${page.rel} states "${figure}" where it quotes run ${singleBucket.runId}, and nothing accounts for it: ` +
            `"${calibration.normalize(block).slice(0, 140)}…"`,
        );
      }
    }
  }

  // 3 · the July figures, only beside the pointer they leave out
  const flat = visible.replace(/\s+/g, ' ');
  for (const figure of NEEDS_THE_POINTER) {
    let at = flat.indexOf(figure);
    while (at !== -1) {
      const around = flat.slice(Math.max(0, at - NEAR), at + figure.length + NEAR);
      if (!/pointer/i.test(around)) {
        fail(
          `${page.rel} states ${figure} with no mention of the pointer near it — that figure left the pointer ` +
            'out, and read on its own it is the cost of a topology that no longer ships',
        );
      }
      at = flat.indexOf(figure, at + figure.length);
    }
  }
}

// ── the benchmarks page's panel on the latest calibration run, every unit and every row ────────────────────
// The whole-page check above reads money only. The panel is the one place the site restates the run in detail —
// counts, shares, sizes — so inside it every figure is held to the evidence, and its rows to the derivation's.
if (singleBucket !== null) {
  const html = fs.readFileSync(path.join(ROOT, 'site', 'benchmarks.html'), 'utf8');
  const open = html.indexOf('id="single-bucket"');
  const close = open === -1 ? -1 : html.indexOf('</div>\n\n', open);
  if (open === -1 || close === -1) {
    fail('site/benchmarks.html no longer has its #single-bucket panel');
  } else {
    const panel = html.slice(open, close).replace(/<!--[\s\S]*?-->/g, '');
    const text = panel.replace(/<[^>]+>/g, ' ').replace(/&nbsp;|&#160;/gi, ' ');
    for (const figure of calibration.unaccounted(text, singleBucket.pageValues)) {
      fail(
        `site/benchmarks.html's #single-bucket panel states ${figure}, which the run does not account for`,
      );
    }
    // Rows: Operation | Per million | Requests. A row that bills a GET or a PUT is one of the derivation's rows,
    // with its cost, and says "expected" if the derivation labels it so; each derived row appears once.
    const body = /<tbody\b[^>]*>([\s\S]*?)<\/tbody>/.exec(panel)?.[1] ?? '';
    if (body === '') fail("site/benchmarks.html's #single-bucket panel has no table body");
    const rows = [...body.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)].map((m) =>
      [...m[1].matchAll(/<t[hd]\b[^>]*>([\s\S]*?)<\/t[hd]>/g)].map((c) =>
        calibration.normalize(c[1].replace(/<[^>]+>/g, '')).trim(),
      ),
    );
    const seen = new Map();
    for (const cells of rows) {
      // A row of another shape is not skipped: a row the check cannot read is a row it does not check.
      if (cells.length !== 3) {
        fail(
          `the #single-bucket panel has a row of ${cells.length} cells, not 3: ${cells.join(' | ')}`,
        );
        continue;
      }
      const [operation, perMillion, requests] = cells;
      const key = requests.replace(/\b(GET|PUT)s\b/g, '$1');
      const want = singleBucket.rows.find((r) => r.requests === key);
      if (want === undefined) {
        fail(`the #single-bucket panel bills "${requests}", which the run does not derive`);
        continue;
      }
      seen.set(key, (seen.get(key) ?? 0) + 1);
      if (perMillion !== want.perMillion) {
        fail(
          `the #single-bucket panel prices "${requests}" at ${perMillion}, not ${want.perMillion}`,
        );
      }
      if ((want.label === 'expected') !== /\bexpected\b/i.test(operation)) {
        fail(`the #single-bucket panel's "${requests}" row must say "expected" exactly when it is`);
      }
    }
    for (const r of singleBucket.rows) {
      if ((seen.get(r.requests) ?? 0) !== 1) {
        fail(
          `the #single-bucket panel has the "${r.requests}" row ${seen.get(r.requests) ?? 0} times, not once`,
        );
      }
    }
  }
}

// ── the spec strip on Home, derived from the source tree ───────────────────────────────────────────────────
// `2 tiers · 4 drivers · 1 third-party dependency` sits under the keys figure on Home. This block anchors that
// strip; `checkDriverCountEverywhere` below anchors every OTHER statement of the same number, on every page.
//
// Both exist because a comment here once claimed Home was the only page stating the count. It was not — five
// pages carried it in a `<p class="meta">` footer and two more spelled it as a word — so removing a driver left
// six stale statements while this gate stayed green, and the claim of exclusivity is what stopped anyone
// looking. A number is only anchored where the gate actually reads it.
//
// The tier count is deliberately NOT anchored. Cache RAM over object storage is the architecture — it cannot
// drift without a rewrite that touches every page and every doc (which is exactly what removing the middle tier
// took), so a check for it is one that CANNOT FAIL, the same reason the bare "22"/"23" calibration quantities
// above are left out. The two figures that CAN drift silently while CI stays green are derived below.
const specAnchors = [];
{
  // A backend counts once, whether it stores the chunks or the pointer — which is now the same answer for all
  // three clouds, since each hosts both. Registry drivers used to be excluded as "a separate axis from the
  // tiering the page is describing", but with one storage tier left the axis the page describes IS this one:
  // which services the library can talk to, and that is what the install line advertises.
  // `Memory` is the in-process dev/test pair and `Retrying` is a decorator wrapping another driver — neither is
  // a backend a reader could point at.
  const NOT_A_BACKEND = new Set(['memory', 'retrying']);
  const backends = new Set();
  const walk = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.ts')) {
        for (const m of fs
          .readFileSync(p, 'utf8')
          .matchAll(/export class (\w+?)(?:Storage|Registry)\w*Driver\b/g)) {
          const backend = m[1].toLowerCase();
          if (!NOT_A_BACKEND.has(backend)) backends.add(backend);
        }
      }
    }
  };
  // EVERY package, not just core. The cloud drivers are their own packages now, so walking only core
  // counted 1 backend where the site claims 4 — the gate caught the move, which is what it is for.
  for (const e of fs.readdirSync(path.join(ROOT, 'packages'), { withFileTypes: true })) {
    if (e.isDirectory()) walk(path.join(ROOT, 'packages', e.name, 'src'));
  }

  // Without this the check is vacuous in the one case that matters most: a refactor that moves or renames the
  // driver classes makes the regex match nothing, and a count of 0 would then "disagree" in a way someone could
  // silence by editing the page rather than the derivation.
  if (backends.size === 0) {
    fail(
      'the driver-count derivation matched no `export class …StorageDriver/…RegistryDriver` under packages/*/src — ' +
        'the classes moved or were renamed, so this check is no longer measuring anything',
    );
  }

  // Third-party (non-workspace) runtime dependencies, PER PACKAGE. `@cloudbitmaps/*` is ours and is declared
  // `workspace:^`, which is what makes the wording "third-party" true where a bare "runtime dependency" is not.
  //
  // This used to read `packages/roaring/package.json` alone and compare it against a site-wide badge saying
  // "1 third-party dependency". That was green and wrong: it answered "how many does the codec have?" while
  // the badge made a claim about the project, sitting directly under an install line for TWO packages. The
  // split gave three storage packages a real cloud SDK each, so a reader following that line gets two
  // third-party deps, not one — and one page stated the badge and "each with its own SDK" in a single
  // sentence. A derivation narrower than the claim it checks cannot fail when the claim goes wrong.
  // EVERY dependency field, not just `dependencies`. An adversarial review moved an AWS SDK into core's
  // `optionalDependencies` and this gate still certified "zero-dependency core" — and the repo has a
  // deliberate rule that nothing is an optional peer, which makes that the most plausible accidental
  // regression of the set.
  const DEP_FIELDS = [
    'dependencies',
    'optionalDependencies',
    'peerDependencies',
    'bundledDependencies',
  ];
  const depsOf = (pkg) => {
    const manifest = JSON.parse(
      fs.readFileSync(path.join(ROOT, 'packages', pkg, 'package.json'), 'utf8'),
    );
    const out = new Set();
    for (const field of DEP_FIELDS) {
      const value = manifest[field];
      if (!value) continue;
      const entries = Array.isArray(value) ? value.map((n) => [n, '']) : Object.entries(value);
      for (const [name, range] of entries) {
        if (String(range).startsWith('workspace:')) continue;
        if (!name.startsWith('@cloudbitmaps/')) out.add(name);
      }
    }
    return [...out];
  };
  const coreDeps = depsOf('core');

  // The badge's premise. If core ever takes a dependency, "zero-dependency core" is false everywhere at once
  // and must be rewritten rather than recounted — so this fails loudly instead of quietly printing a 1.
  if (coreDeps.length !== 0) {
    fail(
      `every page claims a "zero-dependency core", but @cloudbitmaps/core declares ${coreDeps.length} ` +
        `third-party dependenc${coreDeps.length === 1 ? 'y' : 'ies'}: ${coreDeps.join(', ')}`,
    );
  }

  const homeHtml = fs.readFileSync(path.join(ROOT, 'site', 'index.html'), 'utf8');

  // ── no warm-scan ceiling to publish, and the site must not claim one ───────────────────────────────────
  // This block used to derive `DEFAULT_MAX_WARM_SCAN_BYTES` and gate the MiB figure /architecture and /usage
  // quoted for it. Both the constant and the tier it bounded are gone: an intersection's memory is now one
  // term, the chunk-aligned window, with no per-operand delta snapshot outside it. The check is inverted
  // rather than deleted — a page that still quotes a warm ceiling is quoting a bound nothing enforces.
  for (const rel of [
    'site/architecture.html',
    'site/usage.html',
    'site/benchmarks.html',
    'site/index.html',
  ]) {
    const html = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    if (/maxWarmScanBytes/.test(html)) {
      fail(`${rel} names \`maxWarmScanBytes\` — that option no longer exists`);
    }
  }

  // ── the encoding benchmark's factors, wherever /flavors/roaring quotes them ─────────────────────────────
  // That page's table argued adaptivity and offered nothing to check it against — and its "array, bitset and run"
  // row was not even true of the shipped codec until 0.6.0, because roaring's run form takes an explicit pass
  // nothing was making. The factors are published now, so they get a source like every other figure here.
  //
  // ONE rounding rule, computed here rather than transcribed: >=10x rounds to an integer, below that to 2dp.
  // An ad-hoc mix (543 truncated, 63 rounded up, 1.88 to 2dp) is how a gate ends up encoding a typo as a spec.
  const encoding = JSON.parse(
    fs.readFileSync(path.join(ROOT, 'bench', 'encoding-results.json'), 'utf8'),
  );
  const roaringPage = fs.readFileSync(path.join(ROOT, 'site', 'flavors', 'roaring.html'), 'utf8');
  const show = (ratio) => (ratio >= 10 ? String(Math.round(ratio)) : ratio.toFixed(2));
  for (const shape of encoding.shapes) {
    // A shape roaring LOSES is displayed as its reciprocal — the page says "1.02x larger", not "0.98x smaller",
    // because a reader should not have to invert a number to learn we came second.
    const want = shape.roaringSmaller
      ? `${show(shape.vsBestFixed)}\u00d7 smaller`
      : `${show(1 / shape.vsBestFixed)}\u00d7 larger`;
    // Match the WHOLE claim, direction included. An earlier version stripped "smaller"/"larger" and compared
    // only the digits — so the page could have said a shape roaring LOSES was "1.02x smaller" and this would
    // have passed. The direction is the claim; a gate that checks the number but not which way it points is
    // exactly the kind of check that reports coverage it does not have.
    if (!roaringPage.includes(want)) {
      fail(
        `site/flavors/roaring.html does not state the measured factor for the "${shape.shape}" shape ` +
          `as "${want}" — re-run \`pnpm bench:encoding\` and update the page together`,
      );
    } else {
      specAnchors.push([`encoding \u00b7 ${shape.shape}`, want]);
    }
  }

  // ── the soak's combine evidence, where /benchmarks cites it ────────────────────────────────────────────
  // Limitation 04 on that page used to read "the intersection window is not soak-tested", which was true. It now
  // cites two measured figures instead, so they get a source like every other number on the site — the whole
  // point of this file is that no figure is published on the strength of someone having once seen it.
  //
  // The native-creep figure is the load-bearing one. It is the off-heap byte count the roaring addon actually
  // holds, which is where a combine leak WOULD show up and where a JS-heap sample would miss it, so it is quoted
  // to 2dp rather than as "flat" — a reader can tell 0.00 from 0.05, and "flat" hides which one it was.
  // The RSS envelope is a CEILING claim, not a measurement, and it is gated as one.
  //
  // `rss-gate-results.json` records the hard cgroup limit the workload ran under and whether it survived. The
  // per-run measurements in that file (creep, reader RSS) are deliberately NOT gated against the page: they
  // move a little with the machine, and a gate that forces a site edit on every benchmark run is a gate people
  // start skipping. What the page must state is the claim — the ceiling, the workload that ran inside it, and
  // that nothing was OOM-killed.
  //
  // This exists because the gate that produces these numbers ran green on every PR for months while the figure
  // was listed as OWED: the soak ran without SOAK_INJECT, so its verdict lived only in container stdout, and
  // the stage directory is deleted on exit. A measurement nothing records is a measurement nobody has.
  const benchPageForRss = fs.readFileSync(path.join(ROOT, 'site', 'benchmarks.html'), 'utf8');
  const rss = JSON.parse(
    fs.readFileSync(path.join(ROOT, 'bench', 'rss-gate-results.json'), 'utf8'),
  );
  if (rss.oomKilled !== false || rss.verdict !== 'PASS') {
    // A failed run must never become a published envelope. `pnpm rss-gate` exits non-zero on OOM, so a file
    // recording one means it was hand-edited or the gate changed — either way, refuse.
    fail(
      `bench/rss-gate-results.json records verdict=${rss.verdict} oomKilled=${rss.oomKilled} — ` +
        'the site must not cite a failed run as an envelope',
    );
  } else if (!(rss.combines > 0)) {
    // Same reasoning as the zero-combine soak check below: a run that performed no combines never exercised
    // the bound the envelope is about.
    fail('bench/rss-gate-results.json records 0 combines — the envelope would evidence nothing');
  } else {
    for (const [label, want] of [
      ['rss-gate · ceiling', rss.ceiling],
      ['rss-gate · segments', String(rss.segments)],
    ]) {
      if (!benchPageForRss.includes(want)) {
        fail(
          `site/benchmarks.html does not state "${want}" (${label}) — re-run \`pnpm rss-gate\` and update ` +
            'the RSS envelope together',
        );
      } else {
        specAnchors.push([label, want]);
      }
    }
  }

  const soak = JSON.parse(fs.readFileSync(path.join(ROOT, 'bench', 'soak-results.json'), 'utf8'));
  const benchPage = fs.readFileSync(path.join(ROOT, 'site', 'benchmarks.html'), 'utf8');
  if (soak.combines === undefined) {
    fail(
      'bench/soak-results.json has no `combines` field — it predates the combine phase. Re-run `pnpm soak` ' +
        'with SOAK_INJECT=1; a results file from before that phase existed cannot evidence limitation 04.',
    );
  } else if (soak.combines === 0) {
    // The soak itself refuses to report PASS on zero combines, but the *site* must not be able to cite a
    // zero-combine run as evidence either — that would launder "we did not test it" into a published number.
    fail(
      'bench/soak-results.json records 0 combines — /benchmarks must not cite it as combine evidence',
    );
  } else {
    for (const [label, want] of [
      ['soak · combines', String(soak.combines)],
      ['soak · native creep', `${soak.nativeCreepMiB.toFixed(2)} MiB`],
    ]) {
      if (!benchPage.includes(want)) {
        fail(
          `site/benchmarks.html does not state "${want}" (${label}) — re-run \`pnpm soak\` with ` +
            `SOAK_INJECT=1 and update limitation 04 together`,
        );
      } else {
        specAnchors.push([label, want]);
      }
    }
  }

  // ── the invariant count ────────────────────────────────────────────────────────────────────────────────
  // Home's correctness panel used to close on "1,156 of them run on every commit". That was ungated AND already
  // wrong — the suite was at 1,161. An exact test total is the worst figure to publish: it moves on nearly every
  // commit, so gating it breaks CI for anyone who adds a test, and not gating it leaves it stale within a day.
  //
  // The invariant count is the stable number and the one the claim actually rests on, so the page states that
  // instead. CLAUDE.md's "Hard correctness invariants" section is the only enumeration of them in the repo,
  // which makes it the source.
  const claudeMd = fs.readFileSync(path.join(ROOT, 'CLAUDE.md'), 'utf8');
  const invariantSection = /## Hard correctness invariants\n([\s\S]*?)(?=\n## |$)/.exec(claudeMd);
  const invariantCount = invariantSection
    ? (invariantSection[1].match(/^\d+\. \*\*/gm) || []).length
    : 0;
  if (!invariantSection) {
    fail('CLAUDE.md no longer has a "## Hard correctness invariants" section to count');
  } else {
    if (invariantCount === 0) {
      fail(
        "CLAUDE.md's invariants section parsed to 0 numbered items — its list formatting changed, so this " +
          'check is no longer measuring anything',
      );
    }
    const foot = /<p class="ba-foot">([\s\S]*?)<\/p>/.exec(homeHtml);
    if (!foot) {
      fail('site/index.html no longer carries the .ba-foot line that states the invariant count');
    } else {
      const stated = /<strong>(\d+)\s+hard correctness invariants<\/strong>/.exec(foot[1]);
      if (!stated) {
        fail("Home's correctness panel no longer states an invariant count");
      } else if (Number(stated[1]) !== invariantCount) {
        fail(
          `Home says ${stated[1]} hard correctness invariants but CLAUDE.md enumerates ${invariantCount}`,
        );
      } else {
        specAnchors.push(['Home · hard invariants', String(invariantCount)]);
      }
    }
  }

  const strip = /<p class="keys-stats">([\s\S]*?)<\/p>/.exec(homeHtml);
  if (!strip) {
    fail('site/index.html no longer carries the .keys-stats strip that states the driver count');
  } else {
    const stated = new Map();
    for (const m of strip[1].matchAll(/<strong>([\d,]+)<\/strong>\s*([^<]+?)\s*<\/span>/g)) {
      stated.set(m[2].trim(), Number(m[1].replace(/,/g, '')));
    }
    // Checked in BOTH directions, which is the flaw every earlier gate on this site shipped with. Comparing a
    // derived count against a stated one fails when a driver is added and the page is not updated, AND when the
    // page's number is edited away from the truth. `stated.has` covers the third case — the entry being deleted
    // outright, which an equality check alone would never see because there would be nothing to compare.
    for (const [label, want, detail] of [
      ['drivers', backends.size, () => [...backends].sort().join(', ')],
      ['dependencies in @cloudbitmaps/core', coreDeps.length, () => coreDeps.join(', ') || 'none'],
    ]) {
      if (!stated.has(label)) {
        fail(`Home's spec strip no longer states "${label}"`);
      } else if (stated.get(label) !== want) {
        fail(`Home says ${stated.get(label)} ${label} but the source has ${want}: ${detail()}`);
      } else {
        specAnchors.push([`Home · ${label}`, String(want)]);
      }
    }
  }

  // ── the SAME two counts in the hero's meta line ────────────────────────────────────────────────────────
  // Consolidating these into the spec strip came with the claim that each was then "stated once". That was
  // wrong: only the final section's meta line was checked, and the HERO carries them too — in prime position,
  // and in the loose wording ("1 runtime dependency") that the strip had already been corrected away from.
  //
  // Two statements of a figure is fine where they serve different readers, and these do: at-a-glance in the
  // hero, in context beside the tiering further down. What is not fine is one of them being ungated, which is
  // two chances to drift and one place that notices. Both are covered now.
  const heroMeta = /<p class="meta">([\s\S]*?)<\/p>/.exec(homeHtml);
  if (!heroMeta) {
    fail("site/index.html no longer carries the hero's meta line");
  } else {
    for (const [label, want, detail] of [
      ['storage drivers', backends.size, () => [...backends].sort().join(', ')],
    ]) {
      const m = new RegExp(`(\\d+)\\s+${label}`).exec(heroMeta[1]);
      if (!m) {
        fail(`Home's hero meta line no longer states a count for "${label}"`);
      } else if (Number(m[1]) !== want) {
        fail(
          `Home's hero says ${m[1]} ${label} but the source has ${want}: ${detail()} — the spec strip and ` +
            'the hero must agree, and both must agree with the tree',
        );
      } else {
        specAnchors.push([`Home hero · ${label}`, String(want)]);
      }
    }
  }

  // ── the dependency BADGE, on every page carrying the fact strip ────────────────────────────────────────
  // Presence, per line: a fact line making a supply-chain claim must say `zero-dependency core` or name the
  // package it counts, so deleting the claim is as loud as contradicting it. Its premise — core really has
  // no third-party dependencies — is proved once, above.
  //
  // Whether a NUMBERED count names its package is deliberately NOT checked here any more. That rule belongs
  // to every surface, not to `site/`: the two worst instances of the defect were in `README.md` and
  // `SECURITY.md`, which this script does not read. It lives in `tests/docs/dependency-claims.test.ts`,
  // over the whole `git ls-files` corpus, so there is one rule with one home rather than a site-shaped copy.
  // Presence of the badge, on a PINNED list of pages.
  //
  // The previous shape inferred the requirement from the line's own words — a fact line was only required to
  // carry the badge if it still mentioned dependencies, an SDK or a driver count. An adversarial review
  // deleted the badge AND its trigger words from five of the six pages in one edit and the gate stayed
  // green: the condition and the thing it guarded were removed together. A requirement a single edit can
  // switch off is not a requirement, so the list is pinned instead. Adding a page means adding it here,
  // which is a deliberate line in a diff someone reads.
  //
  // /benchmarks is deliberately absent: its meta line is `Apache-2.0 · v0.9.0 · pre-1.0 · single maintainer`
  // and has never made a supply-chain claim.
  const MUST_CARRY_THE_BADGE = [
    'index.html',
    'architecture.html',
    'demo.html',
    'flavors.html',
    'usage.html',
    path.join('flavors', 'roaring.html'),
  ];
  for (const rel of MUST_CARRY_THE_BADGE) {
    const file = path.join(SITE, rel);
    if (!fs.existsSync(file)) {
      fail(
        `site/${rel} is in MUST_CARRY_THE_BADGE but does not exist — update the list or restore the page`,
      );
      continue;
    }
    // Case-insensitive: a sentence-initial "Zero-dependency core" is the same true claim, and rejecting it
    // teaches people to route around the gate rather than to state the scope.
    if (!/zero-dependency core/i.test(fs.readFileSync(file, 'utf8'))) {
      fail(
        `site/${rel} no longer states \`zero-dependency core\`. Every page carrying the fact strip scopes ` +
          'its dependency claim: since the split the codec adds `roaring` and each storage package its own ' +
          'SDK, so an unscoped or absent count is not a smaller claim, it is a wrong one.',
      );
    }
  }

  // …and the same number wherever else any page states it, in digits or in words.
  //
  // The FLOOR is the point. Every hole an adversarial review found in this check announced itself the same
  // way: the tally quietly fell by one while the run stayed green, because a statement that stops matching
  // looks identical to a statement that was deleted. A count that can only go up without a deliberate edit
  // turns both into failures.
  const DRIVER_STATEMENT_FLOOR = 14;
  const alsoChecked = checkDriverCountEverywhere(backends.size);
  if (alsoChecked < DRIVER_STATEMENT_FLOOR) {
    fail(
      `only ${alsoChecked} driver-count statements were found across site/, down from ` +
        `${DRIVER_STATEMENT_FLOOR}. Either a page stopped stating the count, or a phrasing stopped ` +
        'matching — both are how this check has gone quiet before. Lower the floor deliberately if a page ' +
        'really was removed.',
    );
  }
  specAnchors.push(['Site-wide · driver-count statements', String(alsoChecked)]);
}

if (problems.length) {
  console.error('site-figures: the site disagrees with its sources:');
  for (const p of problems) console.error(`  - ${p}`);
  console.error(
    '\n  Sources: bench/results.json (regenerate with `pnpm bench`) · docs/benchmarks.md',
  );
  process.exit(1);
}

const verified = [...anchors.filter(([, v]) => v), ...specAnchors];
console.log(`site-figures: ${verified.length} anchors verified against their sources.`);
for (const [name, v] of verified) console.log(`  ${name.padEnd(24)} ${v}`);
